### ISSUE TITLE
Not able to open site powered by h2o in Firefox

### ISSUE THREAD

**Issue by ramsingla** [h2o/h2o#1000]
I am migrating my site to new servers where I am using h2o.
I am testing my replica site with h2o using new server ip in /etc/hosts

The new site works perfectly with Chrome, Safari but on Firefox the site is not loading. Also, In h2o server log I am not getting any access record logged for the same. There is something not happening correctly at https level.

In firefox when I disable http2 manually, then site works perfectly fine.
network.http.spdy.enabled.http2;false

I saw that your site https://h2o.examp1e.net/ is opening perfectly on Firefox with http2 enabled. Did you also faced similar issue? Can you help me how should I go about debugging and fixing this?

Using

```
h2o version 2.0.1
OpenSSL: LibreSSL 2.2.7
mruby: YES
```
my h2o ssl settings are
```
        ssl-session-resumption:
           mode: all
           lifetime: 3600
        tcp-fastopen: 1
        http2-casper: ON # I am not using the casper feature as of now.
        minimum-version: TLSv1.2
        cipher-preference: server # default: client
        cipher-suite: "HIGH:!aNULL:!MD5 or HIGH:!aNULL:!MD5:!3DES"
        dh-file: /etc/h2o/ssl/dh.pem
        certificate-file: /etc/h2o/ssl/paymango.crt
        key-file: /etc/h2o/ssl/paymango.key
```

Firefox version is 47.0.1 (latest on Mac).

To test out if you put the setting of www.paymango.com and paymango.com to 205.147.109.85
in /etc/hosts and try.
