### ISSUE TITLE
YAML merge not working properly

### ISSUE THREAD

**Issue by pstengel** [h2o/h2o#1007]
Consider this example configuration:

```yaml
hosts:
  "*:80":
    listen: 80
    paths: &default_path
      "/":
        proxy.preserve-host: ON
        proxy.reverse.url:   "http://127.0.0.1:8080"
  
  "*:443": &default_ssl_vhost
    header.set: "Strict-Transport-Security: max-age=31536000"
    listen: &default_ssl_listen
      port:           443
      proxy-protocol: ON
      ssl: &default_ssl_config
        certificate-file:  /opt/h2o/etc/ssl/certs/default.pem
        cipher-preference: server
        cipher-suite:      ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA
        dh-file:           /opt/h2o/etc/ssl/dhparam.pem
        key-file:          /opt/h2o/etc/ssl/private/default.key
        minimum-version:   TLSv1
    paths: *default_path
  
  "example.com:443":
    <<: *default_ssl_vhost
    listen:
      <<: *default_ssl_listen
      ssl:
        <<: *default_ssl_config
        certificate-file: /opt/h2o/etc/ssl/certs/example.com.pem
        key-file:         /opt/h2o/etc/ssl/private/example.com.key
```

Running h2o in test mode results in the following:

```
root@example:/root$ /opt/h2o/bin/h2o -m test -c h2o.conf.sample 
[OCSP Stapling] testing for certificate file:/opt/h2o/etc/ssl/certs/default.pem
fetch-ocsp-response (using OpenSSL 1.0.2g-fips  1 Mar 2016)
sending OCSP request to http://ocsp.comodoca.com
/opt/h2o/etc/ssl/certs/default.pem: good
	This Update: Jul 26 03:13:36 2016 GMT
	Next Update: Jul 30 03:13:36 2016 GMT
verifying the response signature
verify OK (used: -VAfile /tmp/sSjjeZo5he/issuer.crt)
[OCSP Stapling] stapling works for file:/opt/h2o/etc/ssl/certs/default.pem
[OCSP Stapling] testing for certificate file:/opt/h2o/etc/ssl/certs/default.pem
fetch-ocsp-response (using OpenSSL 1.0.2g-fips  1 Mar 2016)
sending OCSP request to http://ocsp.comodoca.com
/opt/h2o/etc/ssl/certs/default.pem: good
	This Update: Jul 26 03:13:36 2016 GMT
	Next Update: Jul 30 03:13:36 2016 GMT
verifying the response signature
verify OK (used: -VAfile /tmp/tlT8zw9rHv/issuer.crt)
[OCSP Stapling] stapling works for file:/opt/h2o/etc/ssl/certs/default.pem
h2o: /usr/src/h2o/lib/core/configurator.c:190: h2o_configurator_apply_commands: Assertion `!"unreachable"' failed.
Aborted
```

However, the sample template is valid YAML and should parse without problems. For example, using Ruby to convert the YAML to JSON and running the result through `jq` for "pretty printing":

```json
root@example:/root$ ruby -rjson -ryaml -e "puts YAML.load(IO.read('/opt/h2o/etc/h2o.conf.sample')).to_json" | jq
{
  "hosts": {
    "*:80": {
      "listen": 80,
      "paths": {
        "/": {
          "proxy.preserve-host": true,
          "proxy.reverse.url": "http://127.0.0.1:8080"
        }
      }
    },
    "*:443": {
      "header.set": "Strict-Transport-Security: max-age=31536000",
      "listen": {
        "port": 443,
        "proxy-protocol": true,
        "ssl": {
          "certificate-file": "/opt/h2o/etc/ssl/certs/default.pem",
          "cipher-preference": "server",
          "cipher-suite": "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA",
          "dh-file": "/opt/h2o/etc/ssl/dhparam.pem",
          "key-file": "/opt/h2o/etc/ssl/private/default.key",
          "minimum-version": "TLSv1"
        }
      },
      "paths": {
        "/": {
          "proxy.preserve-host": true,
          "proxy.reverse.url": "http://127.0.0.1:8080"
        }
      }
    },
    "example.com:443": {
      "header.set": "Strict-Transport-Security: max-age=31536000",
      "listen": {
        "port": 443,
        "proxy-protocol": true,
        "ssl": {
          "certificate-file": "/opt/h2o/etc/ssl/certs/example.com.pem",
          "cipher-preference": "server",
          "cipher-suite": "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA",
          "dh-file": "/opt/h2o/etc/ssl/dhparam.pem",
          "key-file": "/opt/h2o/etc/ssl/private/example.com.key",
          "minimum-version": "TLSv1"
        }
      },
      "paths": {
        "/": {
          "proxy.preserve-host": true,
          "proxy.reverse.url": "http://127.0.0.1:8080"
        }
      }
    }
  }
}
```
