### ISSUE TITLE
Question on .conf file

### ISSUE THREAD

**Issue by gnois** [h2o/h2o#105]
Given the below .conf file:
```
hosts:
  "localhost":
    listen: 8080
    paths:
      /:
        file.dir: examples/doc_root.alternate
    access-log: /dev/stdout
  "localhost":
    listen:
      port: 8081
      ssl:
        certificate-file: examples/h2o/server.crt
        key-file: examples/h2o/server.key
    paths:
      /:
        file.dir: examples/doc_root
    access-log: /dev/stdout
```

The output with curl gives:
```
$ curl http://localhost:8080
hello
$ curl -k https://localhost:8081
hello
```
I was expecting the 2nd output from https would be the index.html file. 
Am I missing something?
Thanks.
