### ISSUE TITLE
Headers not seem to work correctly when adding on host or path.

### ISSUE THREAD

**Issue by nextgenthemes** [h2o/h2o#1056]
```yaml
hosts:

# advancedembeds.com hosts php on HTTP and HTTPS
  "www.advancedembeds.com":
    listen:
      port: 80
    listen:
      port: 443
      ssl: &default_ssl
        cipher-suite: ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS
        certificate-file: /etc/letsencrypt/live/advancedembeds.com/fullchain.pem
        key-file:         /etc/letsencrypt/live/advancedembeds.com/privkey.pem
    paths: &advancedembeds_com_redirect_path
      "/":
        redirect: http://advancedembeds.com/
  "advancedembeds.com":
    header.unset: "Content-Security-Policy" # remove https specific header
    listen:
      port: 80
    listen:
      port: 443
      ssl: *default_ssl
    paths:
      "/":
        file.dir: /diener/advancedembeds.com/php # serve static files if found
        redirect: &php_redirect                  # if not found, internally redirect to /index.php/<path>
          url: /index.php/ # wordpress will have this in the permalink structure by default after install, you probably want to remove this in the wordpress config
          internal: YES
          status: 307

# nextgenthemes.com
  "www.nextgenthemes.com":
    listen:
      port: 80
    listen:
      port: 443
      ssl: &nextgenthemes_com_ssl
        <<: *default_ssl
        certificate-file: /etc/letsencrypt/live/nextgenthemes.com-0001/fullchain.pem
        key-file:         /etc/letsencrypt/live/nextgenthemes.com-0001/privkey.pem
    paths: &nextgenthemes_redirect_path
      "/":
        redirect: https://nextgenthemes.com/
  "nextgenthemes.com:80":
    listen:
      port: 80
    paths: *nextgenthemes_redirect_path
  "nextgenthemes.com:443":
    header.set: "Strict-Transport-Security: max-age=31536000; includeSubDomains; preload"
    listen:
      port: 443
      ssl: *nextgenthemes_com_ssl
    paths:
      "/wp-content/uploads/edd/":
        redirect: https://nextgenthemes.com/
      "/":
        header.set: "Strict-Transport-Security: max-age=31536000; includeSubDomains; preload"
        file.dir: /diener/nextgenthemes.com/php
        redirect: *php_redirect
        
# demo.nextgenthemes.com
  "demo.nextgenthemes.com:80":
    listen:
      port: 80
    paths:
      "/":
        redirect: https://demo.nextgenthemes.com/
  "demo.nextgenthemes.com:443":
    listen:
      port: 443
      ssl:
        <<: *default_ssl
        certificate-file: /etc/letsencrypt/live/demo.nextgenthemes.com/fullchain.pem
        key-file:         /etc/letsencrypt/live/demo.nextgenthemes.com/privkey.pem
    paths:
      "/":
        header.set: "Strict-Transport-Security: max-age=31536000; includeSubDomains; preload"
        file.dir: /diener/demo.nextgenthemes.com/php
        redirect: *php_redirect

# community.nextgenthemes.com
  "community.nextgenthemes.com:80":
    listen:
      port: 80
    paths:
      "/":
        redirect: https://community.nextgenthemes.com/
  "community.nextgenthemes.com:443":
    header.set: "Strict-Transport-Security: max-age=31536000; includeSubDomains; preload"
    listen:
      port: 443
      ssl:
        <<: *default_ssl
        certificate-file: /etc/letsencrypt/live/community.nextgenthemes.com/fullchain.pem
        key-file:         /etc/letsencrypt/live/community.nextgenthemes.com/privkey.pem
    paths:
      "/":
        file.dir: /diener/community.nextgenthemes.com/php
        redirect: *php_redirect

# nico.onl
  "www.nico.onl":
    listen:
      port: 80
    listen:
      port: 443
      ssl: &nico_onl_ssl
        <<: *default_ssl
        certificate-file: /etc/letsencrypt/live/nico.onl-0001/fullchain.pem
        key-file:         /etc/letsencrypt/live/nico.onl-0001/privkey.pem
    paths: &nico_onl_redirect_path
      "/":
        redirect: https://nico.onl/
  "nico.onl:80":
    listen:
      port: 80
    paths: *nico_onl_redirect_path
  "nico.onl:443":
    listen:
      port: 443
      ssl: *nico_onl_ssl
    paths:
      "/":
        header.set: "Strict-Transport-Security: max-age=31536000; includeSubDomains; preload"
        file.dir: /diener/nico.onl/php # serve static files if found
        redirect: *php_redirect

# nicolasjonas.com (Static, no PHP)
  "www.nicolasjonas.com":
    listen:
      port: 80
    listen:
      port: 443
      ssl: &nicolasjonas_com_ssl
        <<: *default_ssl
        certificate-file: /etc/letsencrypt/live/nicolasjonas.com-0001/fullchain.pem
        key-file:         /etc/letsencrypt/live/nicolasjonas.com-0001/privkey.pem
    paths: &nicolasjonas_com_redirect_path
      "/":
        redirect: https://nicolasjonas.com/
  "nicolasjonas.com:80":
    listen:
      port: 80
    paths: *nicolasjonas_com_redirect_path
  "nicolasjonas.com:443":
    listen:
      port: 443
      ssl: *nicolasjonas_com_ssl
    paths:
      "/":
        header.set: "Strict-Transport-Security: max-age=31536000; includeSubDomains; preload"
        file.dir: /diener/nicolasjonas.com/php

# Global settings
user: www-data # default username for webservers on ubuntu/debian... this was a essential thing I needed, found out by trail and error
file.index: [ 'index.php', 'index.html' ] # globally set h2o to look for php files first
access-log: /var/log/h2o/access.log       # you need to create this folder first (common ubuntu/... folder)
error-log: /var/log/h2o/error.log  
pid-file: /var/run/h2o.pid                # (common ubuntu/... folder)
http2-reprioritize-blocking-assets: ON    # performance tuning option

#header.set: "Content-Security-Policy: default-src https:" # This is recommenced but ...
header.set: "Content-Security-Policy: default-src https: 'unsafe-eval' 'unsafe-inline'" # Needed for iframe embeds, edd and svg was not loaded correctly.
# header.set: "Strict-Transport-Security: max-age=31536000; includeSubDomains; preload"  # https://hstspreload.appspot.com says this header should not be send over HTTP so it is set in individial hosts to be served with HTTPS only.
header.set: "X-Content-Type-Options: nosniff"
header.set: "x-frame-options: deny"
header.set: "X-XSS-Protection: 1; mode=block"
file.custom-handler:
  extension: .php
  fastcgi.connect:
    port: /var/run/php/php7.0-fpm.sock
    type: unix
```

As you can see in my config I am trying to add the HSTS `Strict-Transport-Security: max-age=31536000; includeSubDomains; preload` header only to the page when its served over HTTPS because https://hstspreload.appspot.com says this header should not be send over HTTP. As you can see I tried on the host and on the path level. This does not seem to work correctly. https://observatory.mozilla.org/analyze.html?host=nextgenthemes.com I tested it there and also looked at the headers in the browser debug. It seems that the initial HTTP document misses that header but the assets get it correctly. When I added it on a global it worked fine.

The same happens when I try to `header.unset: "Content-Security-Policy" # remove https specific header` on this one host. I have it set globally but I have only one site that I want to server HTTP so I like to set this header globally and then remove it for this one host. Seems to be the same problem as for the HSTS header. The initial HTML document still has the header but its only removed on the assets.

A little off topic but I like to discus and share my config because it took me quite some time to get there. I like to share a config like this in the wiki because it may help others.

- The wiki example mentions WordPress but shows a config with fastcgi php. As far as I know php-fpm is faster and more modern and should be the way to go?
- I needed to add the `user: www-data` because otherwise I could not even get h2o to run, and this was not mentioned in the wiki configs or somewhere around here I think think should be mentioned prominently somewhere and/or added to the example configs. Setting the user may be a good ideo for all linux systems or not? For debian bases its www-data.
- I used yaml aliases and merge but its still feels like a lot of config. Especially the redirect parts from www. to no www and to https at the same time gets repeated a lot. Can this done in a simpler way? Either way I think a config for that would bring value to the wiki.
- In general is there something that could be improved in my config? My next steps is to trying to improve TLS config for better security. So far I just added the cyphers.
