### ISSUE TITLE
poor https performance

### ISSUE THREAD

**Issue by mrhein** [h2o/h2o#1091]
### version

```
⋊> ~ h2o -v
h2o version 2.1.0-DEV
OpenSSL: LibreSSL 2.2.7
mruby: YES
```

### config

```
compress: ON
compress: [ gzip, br ]
file.etag: ON
file.send-compressed: ON
expires: 1 day
ssl-session-resumption:
    mode: all

hosts:
  "test.tld:3080":
    listen:
      port: 3080
    paths:
      "/":
        file.dir: test.tld
      "/stats":
        status: ON
      "/hello":
        mruby.handler: |
          Proc.new do |env|
            [200, {'content-type' => 'text/plain'}, ["Hello world\n"]]
          end
  "test.tld:3443":
      http2-push-preload: ON
      listen:
        port: 3443
        ssl:
          cipher-preference: server
          cipher-suite: ECDHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA
          minimum-version: TLSv1.2
          certificate-file: ./fullchain.pem
          key-file: ./privkey.pem
      paths:
        "/":
          file.dir: test.tld

```

### filedirectory
```
⋊> ~ ls -ahl test.tld/
total 72
drwxr-xr-x    7 mathias  staff   238B Sep 29 11:00 .
drwxr-xr-x+ 269 mathias  staff   8.9K Sep 28 21:29 ..
drwxr-xr-x   13 mathias  staff   442B Sep 28 21:33 .git
-rw-r--r--    1 mathias  staff    12B Sep 22 12:34 README.md
-rw-r--r--    1 mathias  staff    14K Sep 22 12:34 index.html
-rw-------    1 mathias  staff   4.7K Sep 28 21:33 index.html.br
-rw-r--r--    1 mathias  staff   5.6K Sep 22 12:34 index.html.gz
```

### http

```
⋊> ~ wrk -s ~/pipeline.lua -t 1 -c 400 -d 10 http://test.tld:3080/ -- 80
Running 10s test @ http://test.tld:3080/
  1 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    15.97ms    5.50ms  92.91ms   70.20%
    Req/Sec    56.62k     2.97k   63.78k    78.00%
  565485 requests in 10.10s, 7.88GB read
Requests/sec:  56012.77
Transfer/sec:    799.35MB
```

### https

```
⋊> ~ wrk -s ~/pipeline.lua -t 1 -c 400 -d 10 https://test.tld:3443/ -- 80
Running 10s test @ https://test.tld:3443/
  1 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   227.93ms  287.00ms   1.76s    89.39%
    Req/Sec     7.27k     2.07k   12.49k    64.41%
  43772 requests in 10.02s, 624.66MB read
  Socket errors: connect 0, read 0, write 0, timeout 62
Requests/sec:   4369.12
Transfer/sec:     62.35MB
```
