### ISSUE TITLE
file.index

### ISSUE THREAD

**Issue by cbas** [h2o/h2o#1114]
I tried disabling `file.index` and noticed some unexpected behaviour. Not sure if these are bugs. Is there a better way to disable `file.index`?

#### `configuration/test-file.index.yml`
```yml
hosts:
  "localhost:80":
    listen:
      port: 80

    paths:

      # Correct/Expected

      # 200 - Hello world
      "/test_default/":
        file.dir: public

      # 404 - not found
      "/test_not_a_real_file/":
        file.index: ['!']
        file.dir: public

      # Incorrect/Unexpected

      # 403 - access forbidden
      # Doesn't seem to run handlers on this path at all.
      "/test_empty_list/":
        file.index: []
        file.dir: public

      # Infinite 301 redirects, keeps appending "/" to path.
      # Chrome gives up with ERR_TOO_MANY_REDIRECTS.
      # E.g. http://localhost/test_empty_string///////////////////////////////////////////
      "/test_illegal_character/":
        file.index: ['/']
        file.dir: public
      "/test_empty_string/":
        file.index: ['']
        file.dir: public
```
#### `public/index.html`
```html
Hello world
```
#### CLI
```
$ sudo h2o -c configuration/test-file.index.yml
[INFO] raised RLIMIT_NOFILE to 10240
h2o server (pid:16412) is ready to serve requests
```
#### Version
```
$ h2o -v
h2o version 2.1.0-beta3
OpenSSL: LibreSSL 2.4.3
mruby: YES
```
```
$ brew info h2o
h2o: stable 2.0.4 (bottled), devel 2.1.0-beta3
HTTP server with support for HTTP/1.x and HTTP/2
https://github.com/h2o/h2o/
/usr/local/Cellar/h2o/2.1.0-beta3 (110 files, 4.6M) *
  Built from source on 2016-10-31 at 10:56:31 with: --with-libressl --without-openssl@1.1
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/h2o.rb
==> Dependencies
Build: cmake ✔, pkg-config ✔
Recommended: openssl ✔
Optional: libressl ✔, libuv ✘, wslay ✘
```
```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.1
BuildVersion:	16B2555
```
