### ISSUE TITLE
header.unset and use in access-log

### ISSUE THREAD

**Issue by brunohass** [h2o/h2o#1162]
Hello.

We use h2o as a proxy, and when we deliver the data to the client we need to remove some headers, but we use some of these headers in the access log. When we use header.unset, we are no longer able to use the header in the access log.

Example:

```
access-log:
  path: "| rotatelogs /path/to/access-log-file.%Y%m%d 86400"
  format: "%{my-custom-header}o"

header.unset: "my-custom-header"
```

We need to remove the header only on delivery to the client, and be able to capture the header in the access log.

Thank you!
