### ISSUE TITLE
endless redirect cycle

### ISSUE THREAD

**Issue by noogeu** [h2o/h2o#1202]
h2o 2.1.0 (also tried with 2.2.0-DEV) does an endless redirect cycle for the following configuration:

```yaml
user: nobody
compress: ON
fastcgi.timeout.io: 600000

file.custom-handler:
    extension:  .php
    fastcgi.spawn:
        command: "PHP_FCGI_CHILDREN=10 exec /opt/php7/bin/php-cgi"
        user:   nobody

file.index: [ 'index.php', 'index.html', 'index.htm', 'index.txt' ]

hosts:
  "localhost":
    listen:
      port: 80
    paths:
      /:
        file.dir: /srv/www
      /bolt:
        file.dir: /srv/cms/bolt/public
        file.index: [ 'index.php' ]

access-log: /var/log/h2o-access.log
error-log: /var/log/h2o-error.log
pid-file: /run/h2o.pid
```

Now if I do: "wget -S -O- http://localhost/bolt/" then I get a 301 location /bolt,
which goes to http://localhost/bolt, which gives 301 location: /bolt/,
and the cycle continues for 20 times in total.

I tried adding a slash in the configuration to /bolt/: and/or to file.dir: /srv/cms/bolt/public/,
but to no avail. In the first case /bolt is no longer found (as /srv/www/bolt doesn't exist.)

If I wget localhost/bolt/index.php then the page is fetched fine! The file clearly exists.
Removing "file.index: [ 'index.php' ]" doesn't help.

I have something similar with an installation of grav-admin in /srv/www/user/grav-admin/
It also gives an endless cycle with/without trailing slash. Never fetching the index.php which is in that directory. I checked all file permissions, they are readable/searchable everywhere.
php-cgi runs fine, processing index.php okay.

What is the problem?
To me it seems the

**Comment by Varbin** [comment]
I'm not sure but what if you try following:
```yaml
      /bolt/:
        file.dir: /srv/cms/bolt/public
        file.index: [ 'index.php' ]
```
(notice the slash after /bolt) instead of
```yaml
      /bolt:
        file.dir: /srv/cms/bolt/public
        file.index: [ 'index.php' ]
```
Does this fix the issue?
