### ISSUE TITLE
file.dirlisting should display URL path, not internal file path

### ISSUE THREAD

**Issue by dch** [h2o/h2o#125]
given config file:

```yaml
# vi: ft=yaml
# to find out the configuration commands, run: h2o --help
listen: 80
listen:
    port: 443
    ssl:
        minimum-version: TLSv1.2
        certificate-file: server.crt
        key-file: server.key
user: www
access-log: /dev/stdout
file.dirlisting: on
# per-host configuration
hosts:
    "wintermute":
        paths:
            /:
                file.dir: /usr/local/www/data/wintermute
```

the resulting `GET /` is:

```
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 3.2//EN">
<html>
<head>
    <title>Index of /usr/local/www/data/wintermute/</title>
</head>
<body>
    <h2>Index of /usr/local/www/data/wintermute/</h2>
    <ul>
        <li><a href="..">Parent Directory</a></li>
        <li><a href="tmp">tmp</a></li>
    </ul>
</body>
</html>
```

The local server path `/usr/local/www/data/wintermute/` should not be visible to the end user. The HTTP path `/` should be returned instead, for both `<title>` and <`h2`>.
