### ISSUE TITLE
trailing / required for URLs mapped via path

### ISSUE THREAD

**Issue by dch** [h2o/h2o#128]
Using config snippet below to merge multiple URL paths together:

```
hosts:
    "wintermute":
        paths:
            /:
                file.dir: /usr/local/www/data/wintermute
            /poudriere:
                file.dir: /usr/local/poudriere/data/logs/bulk
```

One would expect that the url http://wintermute/poudriere would be accessible, but it's not, only http://wintermute/poudriere/ works -- note trailing slash required in URL.

This is probably not a bug, maybe an FAQ item or a note in docs.
