### ISSUE TITLE
production grade config example

### ISSUE THREAD

**Issue by yannick** [h2o/h2o#1363]
in the examples directory there should be a more advanced example application that showcases a few things:

- production grade TLS settings
- advanced logging 
- load balancing and header replacement / delete headers
- possibly also a few cool mruby tricks

**Comment by dch** [comment]
Here's an improved TLS/security headers version, any comments? I agree more examples would help.

```yaml
# /usr/local/etc/h2o/h2o.conf
# see https://h2o.examp1e.net/ for detailed documentation
user: www
pid-file: /var/run/h2o.pid
access-log: /var/log/h2o/access.log
error-log:  "| logger -4 -i -p daemon.err  -t h2o"

# as of 2017-12-01 the following TLS config and headers gets you:
# A+ on https://www.ssllabs.com/ssltest/
# with DNS CAA records and custom diffie-hellmann parameters
# via `openssl dhparam -out /usr/local/etc/ssl/dhparam.pem 4096`
listen: 80
listen:
  port: 443
  ssl:
    minimum-version: TLSv1.1
    dh-file: /usr/local/etc/ssl/dhparam.pem
    # generate your own certificates
    certificate-file: /usr/local/etc/ssl/acme/example.org/fullchain.pem
    key-file: /usr/local/etc/ssl/acme/private/example.org/privkey.pem
    cipher-preference: server
    cipher-suite: ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK

# A+ on https://securityheaders.io/
header.add: "x-frame-options: deny"
header.add: "X-XSS-Protection: 1; mode=block"
header.add: "X-Content-Type-Options: nosniff"
header.add: "X-UA-Compatible: IE=Edge"
header.add: "Referrer-Policy: strict-origin"
header.add: "Cache-Control: no-transform"
header.add: "Content-Security-Policy: default-src https:"
# 6 months HSTS pinning
header.add: "Strict-Transport-Security: max-age=16000000"

hosts:
  example.org:
    paths:
      "/":
file.dir: "/var/www/example.org"
```
