### ISSUE TITLE
Broken FastCGI?

### ISSUE THREAD

**Issue by xm74** [h2o/h2o#1371]
I'm trying to setup Mailman 2.1 list server with H2O but without success. Mailman installation contains few CGI binaries in _cgi-bin_ subdirectories and one named _listinfo_ generates main index file so I use / path redirection. Here is my config.
```
    "my.server:80"
        listen:
            port: 80
        paths:
            "/":
                redirect:
                    status: 301
                    url: https://my.server/
    "my.server:443"
        listen:
            port: 443
            ssl: *default_ssl
        paths:
            "/":
                redirect:
                    url: /cgi-bin/listinfo
                    internal: YES
                    status: 307
            "/cgi-bin":
                fastcgi.spawn:
                    command: "exec /usr/local/share/h2o/fastcgi-cgi"
            "/icons":
                file.dir: /usr/local/mailman/icons
            "/pipermail":
                file.dir: /usr/local/mailman/archives/public
```
When I trying to connect with I got 503 after 30 sec. timeout.
```
root@beta:/usr/local/mailman # curl -IL http://my.server
HTTP/1.1 301 Redirected
Date: Sun, 16 Jul 2017 21:29:02 GMT
Connection: keep-alive
Server: h2o/2.2.2
location: https://my.server/
content-type: text/html; charset=utf-8

HTTP/2 503
server: h2o/2.2.2
date: Sun, 16 Jul 2017 21:29:32 GMT
content-type: text/plain; charset=utf-8
content-length: 21
```
I also tried to call Mailman's binary directly in **fastcgi.spawn** directive using
```
command: "exec /usr/local/mailman/cgi-bin/listinfo"
```
 but with the same negative result.
Is it bug or I'm doing something wrong?

**Comment by i110** [comment]
@xm74 Please checkout latest master and then try the following configuration.

```
      "/":
        redirect:
          url: /cgi-bin/listinfo
          internal: YES
          status: 307
      "/cgi-bin":
        file.dir: /usr/local/mailman/cgi-bin
        file.custom-handler:
          extension: default # means "no extension" in this case
          fastcgi.spawn:
            command: "exec  /usr/local/share/h2o/fastcgi-cgi"
```
