### ISSUE TITLE
session resumption partly not working

### ISSUE THREAD

**Issue by yannick** [h2o/h2o#1501]
resuming a session from a saved openss s_client works. 
however the server sends new tickets and browsers then use that one, this means that if e.g. session_store redis is used a lot of tickets get created. 
further more with redis store, tickets are not used again if h2o is restarted. 

tested on macos high sierra with https://github.com/h2o/h2o/commit/6b1f65cc1fe3ba5d7b0f7b04114791c072094252 linked against openssl@1.1/1.1.0g

**Comment by kazuho** [comment]
> however the server sends new tickets and browsers then use that one, this means that if e.g. session_store redis is used a lot of tickets get created.

That sounds like an issue. We should not send a session ID if the client supports ticket-based resumption.

> further more with redis store, tickets are not used again if h2o is restarted.

Actually, there is no "redis" ticket-store. We need one.
https://h2o.examp1e.net/configure/base_directives.html#ssl-session-resumption-ticket-based 

> this might all be expected behavior due to how openssl works, however it unclear to me why the session is deleted here:

The session is removed after being provided to OpenSSL in `proceed_handshake` which is called right before.

**Comment by yannick** [comment]
as discussed in chat, clarification its about ssl tokens not tickets. 


```
listen:
  port: 8080
duration-stats: ON
num-threads: 1
http2-graceful-shutdown-timeout: 3
http2-idle-timeout: 1
ssl-session-resumption:
   lifetime: 8640000
   mode: cache
   cache-store: redis
   redis:
     host: localhost 
     port: 6379
hosts:
  "*":
    paths:
      /nstatuz:
        status: ON
    access-log:
      path: /dev/stdout
      format: '{"ssl-id": %{ssl.session-id}x, "connectionId":%{connection-id}x,"sslVersion":"%{ssl.protocol-version}x","sslReused": "%{ssl.session-reused}x","sslCipher":"%{ssl.cipher}x","sslCipherBits":"%{ssl.cipher-bits}x", "http2StreamId": "%{http2.stream-id}x"}'


```

with that config i get new entries in redis and new `ssl.session-id` even though the session is reused
