### ISSUE TITLE
Environment variables via `setenv` are invisible from mruby handler code

### ISSUE THREAD

**Issue by tagomoris** [h2o/h2o#1527]
I want to use some environment variables configured in h2o configuration files, in application code of mruby handler - but it's impossible. ([Document](https://h2o.examp1e.net/configure/base_directives.html#setenv) says that it should be possible.)

I wrote the configuration below:
```yaml
access-log: /dev/stdout
setenv:
  KEY0: "value0"
hosts:
  "localhost":
    listen: 8084
    setenv:
      MRBLIB: /Users/tagomoris/td/bigdam-gateway
      KEY1: "value1"
    paths:
      "/test/env/dump":
        setenv:
          KEY2: "value2"
        mruby.handler: |
          Proc.new do |env|
            obj = {}
            ENV.keys.sort.each do |key|
              obj[key] = ENV[key]
            end
            [200, {'Content-Type' => 'application/json'}, [JSON.dump(obj)]]
          end
```

and executed the command below:

```
curl  http://localhost:8084/test/env/dump | jq .
```

But I couldn't get `KEY*` variables in output:
```json
// only around K
{
  "HOME": "/Users/tagomoris",
  "JENV_LOADED": "1",
  "LANG": "ja_JP.UTF-8",
  "LOGNAME": "tagomoris",
}
```

I've not identified what causes this problem yet, but I think it's a kind of bug.
