### ISSUE TITLE
OS X High sierra from Homebrew - preloads.rb not found.

### ISSUE THREAD

**Issue by d-Pixie** [h2o/h2o#1552]
Hi, I can't find any information regarding this error anywhere so I'm opening a ticket for it.

I just installed h2o via Homebrew, `brew install h2o`, and am trying a minimal example:
```yaml
# h2o.yaml
listen:
  port: 8080
user: nobody
hosts:
  "myhost.example.com":
    paths:
      "/":
        mruby.handler: |
          Proc.new do |env|
            [200, {'content-type' => 'text/plain'}, ["Hello world\n"]]
          end
access-log: ./log/h2o-access.log
error-log: ./log/h2o-error.log
pid-file: ./tmp/pids/h2o.pid
```
Straight from the docs ...
When I try `sudo h2o -m worker -c ./h2o.yaml` in the root of my app I get: `file "/usr/local/Cellar/h2o/2.2.4/share/h2o/mruby/preloads.rb" not found. Did you forget to run `make install` ?Abort trap: 6`...

I verified that the file exists:
```text
$ cat /usr/local/Cellar/h2o/2.2.4/share/h2o/mruby/preloads.rb
require "bootstrap.rb"
require "acl.rb"
include H2O::ACL
```
I have also tried cating the file as noboby:
```text
sudo -u nobody cat /usr/local/Cellar/h2o/2.2.4/share/h2o/mruby/preloads.rb
require "bootstrap.rb"
require "acl.rb"
include H2O::ACL
`
``
And running the server with `user: root` in the config.

I'm out of ideas here. Any idea what is going on?
