### ISSUE TITLE
H2O is using user `h2o` but group `root` and `www-data` on Alpine (OpenRC)

### ISSUE THREAD

**Issue by concatime** [h2o/h2o#1588]
> H2O now setuids to nobody if launched as root and if the user directive is not used.

[Source](//github.com/h2o/h2o/issues/77#issuecomment-74210605).

I'm currently running H2O inside _Alpine Linux (OpenRC)_ with a custom init file launch (See below). H2O is behaving weirdly by running as group `root`, ~~regardless of `user: h2o`~~.

```
 # h2o --version
h2o version 2.2.4
OpenSSL: LibreSSL 2.6.3
mruby: YES
 # grep 'root*' /etc/group
root:x:0:root
bin:x:1:root,bin,daemon
daemon:x:2:root,bin,daemon
sys:x:3:root,bin,adm
adm:x:4:root,adm,daemon
disk:x:6:root,adm
wheel:x:10:root
floppy:x:11:root
dialout:x:20:root
tape:x:26:root
video:x:27:root
 # grep 'www-data' /etc/group
www-data:x:82:h2o,gogs,gitea,nginx
 # install -o gitea -m 710 -d /run/gitea
 # rc-service gitea start
 # rc-service h2o start
 # ls -la /run/gitea
total 0
drwx--x---    2 gitea    root            60 Dec 31 16:19 .
drwxr-xr-x    6 root     root           340 Dec 31 16:21 ..
srw--w----    1 gitea    www-data         0 Dec 31 16:19 gitead.sock
```

Update: I solved the issue with `www-data`. See this [comment](//github.com/h2o/h2o/issues/1588#issuecomment-354705724) below.
.
~~H2O is not able to access the socket file, "failed to connect to host".~~
EDIT: Success, **but it should not**! Only root group should be able to enter the folder!

> The execute bit allows the affected user to enter the directory, and access files and directories inside.

[Source](//unix.stackexchange.com/a/21252).

```
 # chgrp www-data /run/gitea
 # ls -la /run/gitea
drwx--x---    2 gitea    www-data        60 Dec 31 16:40 .
srw--w----    1 gitea    www-data         0 Dec 31 16:40 gitead.sock
```

~~Failed.~~
EDIT: Success as expected.

```
 # chgrp root /run/gitea -R
 # ls -la /run/gitea
drwx--x---    2 gitea    root            60 Dec 31 16:40 .
srw--w----    1 gitea    root             0 Dec 31 16:40 gitead.sock
```

Success, **but it should not**! Only root group should be able to enter the folder and write to the socket!

`/etc/gitea/app.ini`
```ini
[…]
[server]
PROTOCOL = unix
HTTP_ADDR = /run/gitea/gitead.sock
UNIX_SOCKET_PERMISSION = 620
[…]
```

`/etc/h2o.conf`
```yaml
user: h2o
send-server-name: OFF
pid-file:   run/h2o.pid
access-log: var/log/h2o/access.log
error-log:  var/log/h2o/error.log
http2-reprioritize-blocking-assets: ON
hosts:
  'git.concati.me:80':
    listen:
      port: 80
    paths:
      '/':
        redirect:
          status: 301
          url: 'https://git.concati.me'
  'git.concati.me':
    listen:
      port: 443
      ssl:
        key-file: /etc/letsencrypt/live/git.concati.me/privkey.pem
        certificate-file: /etc/letsencrypt/live/git.concati.me/fullchain.pem
        cipher-suite: 'TLS13-AES-256-GCM-SHA384:TLS13-CHACHA20-POLY1305-SHA256:E
CDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-CHACHA20-POLY1305'
        cipher-preference: server
        min-version: TLSv1.2
        max-version: TLSv1.2
    header.add: "Content-Security-Policy: default-src 'none'; style-src 'self';
script-src 'self'; font-src 'self'; img-src 'self' data:"
    header.add: 'Strict-Transport-Security: max-age=63072000'
    header.add: 'X-Content-Type-Options: nosniff'
    header.add: 'X-XSS-Protection: 1; mode=block'
    header.add: 'X-Frame-Options: DENY'
    header.add: 'Referrer-Policy: no-referrer'
    paths:
      '/':
        proxy.reverse.url: 'http://[unix:/run/gitea/gitead.sock]'
        proxy.preserve-host: ON
  'concati.me:80':
    listen:
      port: 80
    paths:
      '/':
        redirect:
          status: 301
          url: 'https://concati.me' # HTTPS
  'concati.me':
    listen:
      port: 443
      ssl:
        key-file: /etc/letsencrypt/live/concati.me/privkey.pem
        certificate-file: /etc/letsencrypt/live/concati.me/fullchain.pem
        cipher-suite: 'TLS13-AES-256-GCM-SHA384:TLS13-CHACHA20-POLY1305-SHA256:E
CDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-CHACHA20-POLY1305'
        cipher-preference: server
        min-version: TLSv1.2
        max-version: TLSv1.2
    header.add: "Content-Security-Policy: default-src 'none'; style-src 'self';
script-src 'self'; font-src 'self'; img-src 'self' data:"
    header.add: 'Strict-Transport-Security: max-age=63072000'
    header.add: 'X-Content-Type-Options: nosniff'
    header.add: 'X-XSS-Protection: 1; mode=block'
    header.add: 'X-Frame-Options: DENY'
    header.add: 'Referrer-Policy: no-referrer'
    paths:
      '/':
        file.dir: /var/www/concati.me
        file.send-compressed: ON
        file.mime.addtypes:
          'text/html; charset=utf-8': .html
        expires: 3 day
      '/assets/images':
        file.dir: /var/www/concati.me/assets/images
        expires: 7 day
```

`/etc/init.d/h2o`
```openrc
#!/sbin/openrc-run
description='H2O ~ Optimized HTTP/S/2 server'
extra_started_commands="reload"
extra_commands="configtest"
pidfile=/run/h2o.pid
depend() {
        need net
        after sshd
        use dns logger netmount
}
start_pre() {
        configtest || return 1
}
start() {
        ebegin "Starting h2o"
        h2o --mode daemon
        eend $?
}
reload() {
        configtest || return 1
        ebegin "Refreshing h2o configuration"
        kill -HUP `cat $pidfile` &>/dev/null
        eend $? "Failed to reload h2o"
}
stop() {
        ebegin 'Stoping H2O configuratoin'
        kill -TERM `cat $pidfile`
        eend $? 'Failed to stop H2O'
}
configtest() {
        # Synonym of `--mode=test`
        MSG=$(h2o --test 2>&1)
        eend $? "$MSG"
}
```

EDIT#1: Added version number.
EDIT#2: Added members of group root
