### ISSUE TITLE
Incorrect value for SCRIPT_NAME in index.php via php-fpm

### ISSUE THREAD

**Issue by JoshyPHP** [h2o/h2o#1630]
I'm investigating h2o as a replacement for nginx and I noticed a discrepancy with regards to `SCRIPT_NAME` in php-fpm processes when serving a default index page.

In my installation, I use `file.index` to set `index.php` as a default index page:

```
file.index: [ 'index.php', 'index.html' ]
hosts:
  "localhost":
    paths:
      "/":
        file.dir: /var/www/localhost
```

h2o displays the correct page when serving `http://localhost/` but phpinfo() shows one difference compared to the same page served through nginx via the same php-fpm process. When the page is served by h2o, the values would be:

Variable | Value
---------|------
$_SERVER['SCRIPT_NAME']     | /
$_SERVER['SCRIPT_FILENAME'] | /var/www/localhost/index.php

Same page served by nginx:

Variable | Value
---------|------
$_SERVER['SCRIPT_NAME']     | /index.php
$_SERVER['SCRIPT_FILENAME'] | /var/www/localhost/index.php

Is there something missing from my configuration or is that a bug?

**Comment by proyb6** [comment]
Try remove ```file.index```? I haven't test at this point.

**Comment by kazuho** [comment]
Thank you for reporting the issue.

I haven't checked nginx, but I have confirmed that the mod_cgi module of Apache HTTP server works the same way as nginx does. Hence calling this a H2O bug.

**Comment by i110** [comment]
@JoshyPHP What version of h2o are you using? I tried both of v2.2.4 and current master with the following configuration, but I saw SCRIPT_NAME is `/` like nginx.

```
file.custom-handler:
    extension: .php
    fastcgi.connect: 9120 # listened by php-fpm
file.index: [ 'index.php', 'index.html' ]
hosts:
  "localhost":
    paths:
      /:
        file.dir: /path/to/my/doc_root
```

![image](https://user-images.githubusercontent.com/969287/35918029-aba1e466-0c53-11e8-90ea-c3b9a3360a4a.png)
