### ISSUE TITLE
Reverse proxy configuration

### ISSUE THREAD

**Issue by proyb6** [h2o/h2o#1640]
I'm not sure how to correctly configure reverse proxy on H2O while I have success with Nginx. The Wiki is missing out some bits.

H2O
```
host:
 "localhost:9099":
   listen:
      port: 9099
      ssl:
        certificate-file: /opt/h2o/cert_chain.crt
        key-file: /opt/h2o/myserver.key
   paths:
     "/proxy":
       proxy.reverse.url: https://127.0.0.1:4430/
#       proxy.preserve-host: ON
```

Nginx
```location / {
          proxy_pass https://127.0.0.1:4430;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-NginX-Proxy true;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_read_timeout 3m;
          proxy_send_timeout 3m;
        }
```
