### ISSUE TITLE
stace found errors on open files with ENOENT

### ISSUE THREAD

**Issue by proyb6** [h2o/h2o#1697]
I wonder in the strace I have inspected ```strace -v -o calls.txt -e open,stat,access,accept4 -p ###``` ### is pid number. I assume I have defined webp as not compressible, how did the open system call still search for br and gz?

I not sure what is ```accept4``` error.

```
accept4(4, NULL, NULL, SOCK_CLOEXEC|SOCK_NONBLOCK) = 8
accept4(4, NULL, NULL, SOCK_CLOEXEC|SOCK_NONBLOCK) = -1 EAGAIN (Resource temporarily unavailable)
open("/var/h2o/www/css/t.css.br", O_RDONLY|O_CLOEXEC) = 12
open("/var/h2o/www/fonts/or.woff2.br", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/var/h2o/www/fonts/or.woff2.gz", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/var/h2o/www/fonts/or.woff2", O_RDONLY|O_CLOEXEC) = 13
open("/var/h2o/www/webp/img/slide1-480.webp.br", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/var/h2o/www/webp/img/slide1-480.webp.gz", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/var/h2o/www/webp/img/slide1-480.webp", O_RDONLY|O_CLOEXEC) = 14

```

H2O.conf
```
compress: off

file.mime.settypes:
    "image/webp":
         extensions: [".webp"]
         is_compressible: no
         priority: normal
```
