### ISSUE TITLE
Restful URL path

### ISSUE THREAD

**Issue by proyb6** [h2o/h2o#1699]
I came across a YAML could define a ```{id}``` Restful parameter?
https://gist.github.com/crrobinson14/8290174#file-books-yml

I don't think it's available on H2O and it's useful to handle multiple Restful parameters.

YAML 
```
paths:
  "/books/{category}/{id}"
        book_type: category
        book_id: id
```
