### ISSUE TITLE
I/O error (head)

### ISSUE THREAD

**Issue by consti** [h2o/h2o#1710]
Sorry in advance if this is the wrong repository to report the issue - I'm not sure if it belongs here or at [Puma](https://github.com/puma/puma).

I've been trying to setup h2o (v2.2.4, LibreSSL 2.4.5) as a reverse proxy in front of Puma (master release) to make use of early hints in Rails 5.2.0rc2.

Unfortunately it only works for a few requests, then h2o returns 502 with a `I/O error (head)` error.

I'm not sure what I'm doing wrong - I've tried different flags and configurations - this is what I currently have:

```yaml
access-log: /var/log/h2o/access-log
error-log: /var/log/h2o/error-log

hosts:
  "consti.de":
    listen:
      port: 80
    listen:
      port: 443
      ssl:
        certificate-file: /etc/letsencrypt/live/consti.de/fullchain.pem
        key-file: /etc/letsencrypt/live/consti.de/privkey.pem
        minimum-version: TLSv1
        cipher-suite: ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK
    paths:
      "/":
        proxy.reverse.url: http://[unix://var/www/cblog/shared/tmp/sockets/puma.sock]
        proxy.preserve-host: ON # Preserve original host to satisfy Forgery Protection
        proxy.timeout.keepalive: 0
      "/assets": # serve asset files directly
        gzip: ON
        file.dir: /var/www/cblog/shared/public/assets
      "/.well-known":
        file.dir: /var/www/html/cblog/.well-known
```

I've tried different values for `proxy.timeout.keepalive`; I've also tried setting `proxy.timeout.io` - that also didn't help.

Puma doesn't have a timeout value that I could set - in Puma:

```ruby
threads 5, 5
bind "unix://var/www/cblog/shared/tmp/sockets/puma.sock"
early_hints true
prune_bundler
```

I also tried running puma as a service listening on a port (e.g. 3000) and then use that as reverse.url (e.g. 'http://localhost:3000'). That resulted in the same flunky connection. If I hit the URL locally (`curl -I http://localhost:3000`) then no such error occurs.

If someone who got this running could share her/his configuration, that would be great!
