### ISSUE TITLE
Independent element for YAML anchors

### ISSUE THREAD

**Issue by ndac-todoroki** [h2o/h2o#1738]
related: #741

Reading the docs, I get that I can define an anchor inside some pre-defined element(s), as shown in the issue above:

```yaml
hosts:
  "example.com":
    listen:
      port: 443
      ssl:
        certificate-file: /path/to/example.com.crt
        key-file:         /path/to/example.com.crt
    paths:  &default_paths
      "/":
        file.dir: /path/to/doc-root
  "example.org":
    listen:
      port: 443
      ssl:
        certificate-file: /path/to/example.org.crt
        key-file:         /path/to/example.org.crt
    paths:  *default_paths
```

But it gets harder to read when your config file gets bigger. I tried cutting all anchors out:

```yml
anchors:
  https_settings: &https
    port: 443
  default_paths:  &default_paths
    "/":
      file.dir: /path/to/doc-root

hosts:
  "example.com":
    listen:
      <<: *https
      ssl:
        certificate-file: /path/to/example.com.crt
        key-file:         /path/to/example.com.crt
    paths:  *default_paths
  "example.org":
    listen:
      <<: *https
      ssl:
        certificate-file: /path/to/example.org.crt
        key-file:         /path/to/example.org.crt
    paths:  *default_paths
```

without any luck. I get `Apr 25 21:47:27 ip-10-0-0-65 h2o[4530]: [/etc/h2o/h2o.conf:1] unknown command: anchors` error logs.

Do we already have some predefined namespace (element) to do things like this? If not, I really want to have something like this, where things included in that particular element (`anchors`) will just be interpolated.
