### ISSUE TITLE
2.3.0-beta1: mruby: h2o responds HTTP Date header twice when 399

### ISSUE THREAD

**Issue by chabu** [h2o/h2o#1777]
Is this the expected behavior?

config:
```yaml
listen:
  port: 8080

hosts:
  default:
    paths:
      "/":
        mruby.handler: |
          lambda do |env|
            return [399, {}, []]
          end
        file.dir: /path/to/directory
```

do `curl -v http://h2o.local:8080/`:
```
< HTTP/1.1 200 OK
< Connection: keep-alive
< Content-Length: 4047
< Server: h2o/2.3.0-beta1
< date: Sun, 03 Jun 2018 07:06:50 GMT
< date: Sun, 03 Jun 2018 07:06:50 GMT
< content-type: text/html
< last-modified: Sat, 12 May 2018 16:00:00 GMT
< etag: "5af70f80-fcf"
< accept-ranges: bytes
```
