### ISSUE TITLE
Rewrite

### ISSUE THREAD

**Issue by panaceya** [h2o/h2o#1791]
Hello!

I need rewrite to /index.php?_arg=URI, if requested file not exist.

Example in nginx

```
location / {
    try_files $uri $uri/ /index.php?_arg=$uri;
}
```
This example rewrite to /ndex.php, but no /index.php?_arg=URI
```
    paths:
      "/":
        file.dir: /var/www/
        redirect:
          url: /index.php/
          internal: YES
          status: 307
```
Please help.
