### ISSUE TITLE
Cannot set header.unset on host or path level

### ISSUE THREAD

**Issue by proyb6** [h2o/h2o#1828]
I don't know if I could unset/set/add header in path level that has been defined in global level or was it because of internal 307 redirect?

```
**header.set: "Content-Security-Policy: ..."**

  paths:
    "/":
      **header.unset: "Content-Security-Policy"**
      header.set: "settest: 1"
      header.add: "addtest: 1"
      mruby.handler-file: /var/h2o/mrubywp/wpsupercache.rb
      file.dir: /var/www
      redirect:
        url: /index.php/
        internal: YES
        status: 307
      file.send-compressed: on
```

I found someone with similar issue and haven't seen any solutions https://github.com/h2o/h2o/issues/1056
