### ISSUE TITLE
Gitea

### ISSUE THREAD

**Issue by sleepycodernotes** [h2o/h2o#2032]
can someone help me with reverse proxy?
nginx looks like :

upstream gitea {
    server 127.0.0.1:3000;
}

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name example.com;
    root /var/lib/gitea/public;
    access_log off;
    error_log off;

    location / {
      try_files maintain.html $uri $uri/index.html @node;
    }

    location @node {
      client_max_body_size 0;
      proxy_pass http://localhost:3000;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_max_temp_file_size 0;
      proxy_redirect off;
      proxy_read_timeout 120;
    }
}

need same configuration in /etc/h2o/h2o.conf

**Comment by utrenkner** [comment]
I don't have the time to translate everything for you. But this is the most important part of my h2o.conf concerning Gitea:

```
"<mydomain>:443":
  listen:
    host: <ipv6_address>
    port: 443
    ssl: &ssl_git
      certificate-file: /path/to/fullchain.pem
      key-file: /path/to/privkey.pem
      cipher-preference: server
      cipher-suite: ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDSA-SECP256R1-SHA256:ECDSA-SECP384R1-SHA384:ECDSA-SECP521R1-SHA512:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RS
A-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-
SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS
      dh-file: /path/to/dhparams.pem
  listen:
    host: <ipv4_address>
    port: 443
    ssl: *ssl_git
  paths:
    "/":
      proxy.reverse.url: "http://<ipv4_address_gitea>:3000/"
```
Just replace the things marked <something> with your values.
