### ISSUE TITLE
failed to resize temporary file: No error: 0

### ISSUE THREAD

**Issue by iron-udjin** [h2o/h2o#2084]
Hello,

I running h2o-2.2.5_3 on FreeBSD 12. When I try to upload file into Django admin I getting an error: 
> failed to resize temporary file: No error: 0

Chromium shows error: ERR_SPDY_PROTOCOL_ERROR

h2o is configured as a reverse proxy for uwsgi backend which works in HTTP mode:

```
    paths:
      /:
        proxy.reverse.url: http://[unix:/tmp/http-api.sock]
        proxy.preserve-host: ON
        proxy.timeout.io: 300000
        proxy.timeout.keepalive: 30000
```

Tell me please, why does it happen and how can I fix it?

Thank you!
