### ISSUE TITLE
Proxy websocket always return 403

### ISSUE THREAD

**Issue by MiyamuraMiyako** [h2o/h2o#2131]
In access log: "GET /payment/ HTTP/1.1" 403 10 "-" "Go-http-client/1.1"
My client received Http 403.

Below is my config:
```yaml
access-log: /tmp/h2o.log
error-log: /tmp/h2o.err
pid-file: /tmp/h2o.pid
max-connections: 51200
file.send-gzip: ON
tcp-fastopen: 3
user: www
http2-reprioritize-blocking-assets: ON
file.index: [ 'index.php', 'index.html' ]
hosts:
  "domain.com:443":
    header.add: "strict-transport-security: max-age=39420000; includesubdomains; preload"
    header.add: "X-Frame-Options: SAMEORIGIN"
    header.add: "X-Content-Type-Options: nosniff"
    header.add: "X-XSS-Protection: 1; mode=block"
    header.add: "Access-Control-Allow-Origin: *"
    listen:
      port: 443
      ssl:
        certificate-file: /home/ssl/crt.crt
        key-file: /home/ssl/key.key
        minimum-version: TLSv1.1
        cipher-preference: server
        cipher-suite: CHACHA20 EECDH+ECDSA+AESGCM EECDH+aRSA+AESGCM EECDH+ECDSA+SHA384 EECDH+ECDSA+SHA256 EECDH+aRSA+SHA384 EECDH+aRSA+SHA256 EECDH+aRSA+RC4 EECDH EDH+aRSA !aNULL !eNULL !LOW !3DES !MD5 !EXP !PSK !SRP !DSS !RC4
    paths:
      "/":
        file.dir: /home/wwwroot/domain.com/
      "/payment/":
        proxy.reverse.url: "http://127.0.0.1:3722/payment/"
        proxy.preserve-host: ON
        proxy.websocket: ON
        proxy.header.add: "Origin: "
```
