### ISSUE TITLE
How to specify domain ?

### ISSUE THREAD

**Issue by Fover23** [h2o/h2o#2163]
I want to specify the domain.
My configure file is:
```yaml
hosts:
  "t.mydomain.cn":
    listen:
      port: 8080
    paths:
      "/":
        proxy.reverse.url: "http://127.0.0.1:9000"
    access-log: /dev/stdout
    compress: ON
    compress-minimum-size: 1024
pid-file: /tmp/h2o.pid
```
I hava other domain such as (b.mydomain.cn) to point the same VPS,two domains are worked,but I just want the t.mydomain.cn work and other domain just return http 403 or other http state.

How to configure?
