### ISSUE TITLE
How to log the backend IP address?

### ISSUE THREAD

**Issue by ibantxo** [h2o/h2o#2238]
Hi, 

h2o version 2.3.0-DEV@7081e14e
OpenSSL: LibreSSL 3.0.2

I have a config:
```
hosts:
  "*":
    listen:
      port: 80
    paths:
      "/":
        proxy.reverse.url: http://127.0.0.1:6081/
```

I am logging:
```
access-log:
  escape: apache
  path: "| logger -i -p daemon.info -t h2o"
  format: "[%s] @%h %V%U%q %{Referer}i - %b - %{total-time}x"
```

But %h logs request IP. I want to log "remote IP" ("backend IP")

What parameter % could be used?

Many thanks in advance

Iban
