### ISSUE TITLE
Multiple backend servers configuration

### ISSUE THREAD

**Issue by tetsuya28** [h2o/h2o#2292]
I setup h2o with this [doc](https://h2o.examp1e.net/configure/proxy_directives.html#proxy.reverse.url) for proxy server, and I edited the h2o conf with...
```
proxy.reverse.url:
  backends:
    - http://10.0.0.1:8080/
    - http://10.0.0.2:8080/
  balancer: least-conn
```

I got an error 
line 23 is `backends:`

```
 [/etc/h2o/h2o.conf:23] in command proxy.reverse.url, argument cannot be a mapping
```
