### ISSUE TITLE
Need a !join directive to have relative paths

### ISSUE THREAD

**Issue by cyisfor** [h2o/h2o#2360]
Need something like this:

```yaml
...
  root: &root /usr/share/h2o
  logs: !join [ *root, "logs" ]
  docroot: !join [ *root, "sites" ]
...
  hostname: &hostname "somesite.domain.org"
  access-log: !join [ *logs, "/", *hostname, "/access.log" ]
  paths:
    "/":
      file.dir: !join [ *docroot, "/", *hostname ]
```

So that we don't have to write this sort of highly coupled duplicated code:

```yaml
  host: &host "somesite.domain.org"
  access-log: /usr/share/h2o/logs/somesite.domain.org/access.log
  paths:
    "/":
      file.dir: /usr/share/h2o/sites/somesite.domain.org
...
  hostname: "someothersite.domain.org"
  access-log: /usr/share/h2o/logs/someothersite.domain.org/access.log
  paths:
    "/":
      file.dir: /usr/share/h2o/sites/someothersite.domain.org
...
```

What would be really awesome is if those YAML merge things had lazy evaluation, so like
```yaml
template: &template
  access-log: !join [ *logs, "/", *host, "/access.log" ]
   "/":
      file.dir: !join [ *docroot, "/", *host ]
...
  <<: *template
  hostname: "somesite.domain.org
...

  <<: *template
  hostname: "someothersite.domain.org
...
```

But at the very least it'd make configuration more portable and easier to switch domains and roots if you could join together a list of alias nodes and other things into a single string.
