### ISSUE TITLE
Strict Server Name Indication (SNI)

### ISSUE THREAD

**Issue by Tintinabula** [h2o/h2o#2404]
What is the preferred H2O method to deny clients who do not provide Server Name Indication (SNI) upon connection?

Out goal is to restrict access to only SNI aware clients. H2O should refuse to negotiate TLS with non-SNI clients and immediately drop/disconnect the connection.

Could a "strict SNI" check directive be a worthy enhancement to H2O?

For example, both Apache and HAProxy provide an SNI check directive:

Apache
  SSLStrictSNIVHostCheck on

"sets whether a non-SNI client is allowed to access a name-based virtual host.  If set to on in the default name-based virtual host, clients that are SNI unaware will not be allowed to access any virtual host, belonging to this particular IP / port combination. If set to on in any other virtual host, SNI unaware clients are not allowed to access this particular virtual host."

HAProxy
  strict-sni

"The SSL/TLS negotiation is allowed only if the client provides a SNI that matches a certificate loaded by HAProxy. The default certificate is ignored in this case."

Nginx, unfortunately, does not have an SNI check so we must create an empty self-signed certificate and apply that certificate to a default server block. Then create a second server block defining our valid host name and assign our public ssl certificate to this second server block. This hack will deny clients who are SNI unaware and those clients scanning ip addresses because non-SNI clients always negotiate with the empty self-signed certificate.

Thanks for your time.

**Comment by Tintinabula** [comment]
For now we decided to use the Nginx empty self-signed certificate hack for H2O.

For those interested, create an empty self-signed certificate. We chose an ECDSA certificate but RSA will work too. Make note of the path the files are created in for the h2o.conf

```
openssl ecparam -name secp521r1 -genkey -param_enc explicit -out default_key.pem
openssl req -new -x509 -key default_key.pem -out default_crt.pem -days 1000
```

In the h2o.conf , the first hosts: section is the default, catch-all server block which will define the empty self-signed certificate. The next hosts: section defines the valid hostname "example.org" and public ssl certificate.

```
# Default catch-all domain, empty self-signed certificate
hosts:
  "null":
   listen:
     host: 0.0.0.0
     port: 443
     ssl:
        certificate-file: /certificate_self_null/default_crt.pem
        key-file:         /certificate_self_null/default_key.pem
        ocsp-update-interval: 0
        neverbleed: off
   paths:
     /:
       file.dir: /dev/null

# Example.org domain, client required Server Name Indication (SNI
hosts:
  "example.org":

   # ssl
   listen: &ssl_quic
     host: 0.0.0.0
     port: 443
     ssl:
        certificate-file: /username/.acme.sh/example.org_ecc/fullchain.cer
        key-file: /username/.acme.sh/example.org_ecc/example.org.key
        min-version: TLSv1.3
        ocsp-update-interval: 0
        neverbleed: off

   listen:
     <<: *ssl_quic
     type: quic

   paths:
     /:

( then the rest of your config...)
```

You can test SNI compliance with a curl head request . If you use the hostname "example.org" the return code should be 200. If the ip address is used, in this case example.org points to 192.168.0.1, then ssl fails to negotiate the empty self-signed certificate which is the desired response.

```
curl -kIL https://example.org
HTTP/2 200 

curl -kIL https://192.168.0.1
curl: (35) error:1414D17A:SSL routines:tls12_check_peer_sigalg:wrong curve
```

I will keep this ticket open for a little while in case there are any comments.
