### ISSUE TITLE
custom-handler: extension: default causes h2o to not restart

### ISSUE THREAD

**Issue by RobBelics** [h2o/h2o#2465]
According to the documentation, adding "extension: default" should allow cgi files to be executed without an extension.
```
file.custom-handler:
                    extension: default
                    fastcgi.spawn:
                        command: "exec /usr/local/mycgifile"
```
When h2o is restarted, `service h2o restart` an error occurs:

> Stopping h2o.
> Starting h2o.
> [/usr/local/etc/h2o/h2o.conf:70] in command file.custom-handler, given extension "default" does not start with a "."
> /usr/local/etc/rc.d/h2o: WARNING: failed to start h2o
> 

This issue is on FreeBSD 12.1-RELEASE-p9

If I change the extension value to `.html`, h2o restarts and the cgi program is properly executed when called.
