### ISSUE TITLE
failed to stop when using merge files, it hangs

### ISSUE THREAD

**Issue by vegnuli** [h2o/h2o#2563]
i use lasted h2o and use a simple merge file:

h2o.conf

```
user: www-data
pid-file: /run/h2o.pid
listen:
  port: 80
hosts:
  default:
    paths:
      <<: !file /etc/h2o/h2o_hosts.conf
```

h2o_hosts.conf
```
      /:
        file.dir: /var/www/html
```

when i try to stop does not workl and it hangs.. 

found that the culprit is the merge feature, puting a comment in the merge line works

```
user: www-data
pid-file: /run/h2o.pid
listen:
  port: 80
hosts:
  default:
    paths:
#      <<: !file /etc/h2o/h2o_hosts.conf
```

and now can stop normally.. using systemd unit or init sysv or rc file script daemon..
