### ISSUE TITLE
fails to start if merged/included file is just comments

### ISSUE THREAD

**Issue by mckaygerhard** [h2o/h2o#2565]
usin merge file if the merged file just have commented lines h2o will cras and does not start, as example:

h2o.conf

```
user: www-data
pid-file: /run/h2o.pid
listen:
  port: 80
hosts:
  default:
    paths:
      /:
        file.dir: /var/www/html
      <<: !file /etc/h2o/h2o_inclusion.conf
```

h2o_inclusion.conf
```
# comment in the merged file
```

log says:

```
..uration file /etc/h2o/h2o_inclusion.conf line 1 (included from file /etc/h2o/h2o.conf line 10): (null)
..uration file /etc/h2o/h2o.conf line 10: tag resolution failed
```

is clear check the "null" cos interprete the file as empty content! this error must be ignored!

**PD**: please when solved , include the commit or mR here in a comment.. thanks !
