### ISSUE TITLE
h2o will SIGABRT on FreeBSD 10.1 (seems random)

### ISSUE THREAD

**Issue by Tintinabula** [h2o/h2o#264]
H2O will SIGABRT requiring a restart of the daemon.

The daemon may die after an hour or stay up for 12 hours. The SIGABRT seems to be random. The same h2o build was tested on two different machines with FreeBSD. The server is accepting public internet traffic, but I do not know if this is the cause of the SIGABRT. The daemon will not die when I throw random data at the server or when the daemon is hit with an Apache bench tool. The h2o log file does not contain any suspicious activity after the crash. No core dump file when the h2o daemon dies. I am assuming that h2o is calling an abort() call itself.

If you have any suggestions to collect more debug information I would be happy to diagnose the issue and report my findings.

```
# OS type
root@NIFON:  freebsd-version
10.1-RELEASE-p8

# hardware
root@NIFON:  dmesg | grep CPU:
CPU: AMD A8-7600 Radeon R7, 10 Compute Cores 4C+6G   (3094.43-MHz K8-class CPU)

# Build options, using the built in libressl and yaml libs
root@NIFON:  cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_CXX_FLAGS="-Wall
  -O2 -fstack-protector-all -ggdb3 -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security
  -std=c++0x -fvisibility=hidden" -DCMAKE_C_FLAGS="-Wall -O2 -fstack-protector-all
  -ggdb3 -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fvisibility=hidden" .
   && make && make install

# version, github pull on Thurs, Apr 02, 2015 @ 0902 GMT
root@NIFON:  /usr/local/bin/h2o -v
h2o version 1.1.2-alpha1

# Start h2o

root@NIFON: /usr/local/bin/h2o --conf /etc/h2o.conf

root@NIFON:  pgrep h2o
96205

# gdb debug

root@NIFON:  gdb /usr/local/bin/h2o 96205
GNU gdb 6.1.1 [FreeBSD]
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "amd64-marcel-freebsd"...
Attaching to program: /usr/local/bin/h2o, process 96205
Reading symbols from /lib/libthr.so.3...done.
[New Thread 801407800 (LWP 100442/h2o)]
[New Thread 801407400 (LWP 100441/h2o)]
[New Thread 801406c00 (LWP 100440/h2o)]
[New Thread 801406800 (LWP 100439/h2o)]
[New Thread 801406400 (LWP 100729/h2o)]
Loaded symbols for /lib/libthr.so.3
Reading symbols from /lib/libc.so.7...done.
Loaded symbols for /lib/libc.so.7
Reading symbols from /libexec/ld-elf.so.1...done.
Loaded symbols for /libexec/ld-elf.so.1
[Switching to Thread 801407800 (LWP 100442/h2o)]
0x0000000800d2604a in kevent () from /lib/libc.so.7
(gdb) bt
#0  0x0000000800d2604a in kevent () from /lib/libc.so.7
#1  0x0000000000407c01 in h2o_evloop_run (loop=0x80240e040) at kqueue.c.h:124
#2  0x000000000043cc23 in run_loop (_thread_index=0x3) at /storage/builds/h2o/src/main.c:1195
#3  0x00000008009e64f5 in pthread_create () from /lib/libthr.so.3
#4  0x0000000000000000 in ?? ()
(gdb) c
Continuing.

     (...after about 6.5 hours the daemon crashed.)

Program received signal SIGABRT, Aborted.
[Switching to Thread 801407400 (LWP 100441/h2o)]
0x0000000800c6f6ca in thr_kill () from /lib/libc.so.7
(gdb) c
Continuing.

Program terminated with signal SIGABRT, Aborted.
The program no longer exists.
(gdb)
```

The config file:
```
# h2o config - https://calomel.org/h2o.html

listen:
    host: 127.0.0.1
    port: 80
listen:
    host: 127.0.0.1
    port: 443
    ssl:
        certificate-file: /ssl_keys/example.org_ssl.crt
        key-file: /ssl_keys/example_ssl.key
        cipher-preference: server
        cipher-suite: ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256
        minimum-version: TLSv1.2

access-log: /var/log/h2o_access.log
expires: 1 year
file.dirlisting: off
file.send-gzip: on
#http1-request-timeout: 10
#http2-idle-timeout: 10
limit-request-body: 1024
#max-connections: 1024
#num-threads: 4
pid-file: /var/run/h2o.pid
user: daemon

file.mime.addtypes:
   application/atom+xml: .xml
   application/zip: .zip

header.set: "strict-transport-security: max-age=39420000; includesubdomains; preload"
header.set: "content-security-policy: default-src 'none';style-src 'unsafe-inline';img-src https://example.org data:"
header.set: "x-frame-options: deny"

hosts:
   example.org:
     #enforce-https: on  (not available yet)
         paths:
           /:
              file.dir: /data/htdocs/

```
