### ISSUE TITLE
Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384

### ISSUE THREAD

**Issue by CarloMartini** [h2o/h2o#2688]
Hello,
Is it possible to make h2o accept the cipher in the title? More precisely:

https://ciphersuite.info/cs/TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384

We have a client requiring this, and up to now we have been unsuccessful when trying it out. Thank you

**Comment by CarloMartini** [comment]
Hello,
I never got any reply, so could you at least tell where I can find the list of supported ciphers?

The problem is I have a whole server that must continue using deprecated and unsecure TLS protocols because safer solutions don't seem viable. The service I'm working would be compatible with:

0xc02c | TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 | ECDHE-ECDSA-AES256-GCM-SHA384
0xc02b | TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 | ECDHE-ECDSA-AES128-GCM-SHA256

**Comment by TheDecryptor** [comment]
H2O uses the same cipher suite strings as OpenSSL (mentioned [here](https://h2o.examp1e.net/configure/base_directives.html#listen)), so `ECDHE-ECDSA-AES256-GCM-SHA384` is what you want. Here's my configuration

```yaml
listen:
    port:   443
    ssl:
        minimum-version:    TLSv1.2
        cipher-suite:       "ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384"
```

For TLS 1.2 you need a ECDSA server certificate to use this suite though, if you've only got an RSA one then it simply won't work.
