### ISSUE TITLE
Connections may remain in CLOSE_WAIT forever when proxying

### ISSUE THREAD

**Issue by cbay** [h2o/h2o#2816]
Tested on the current master (772568b) with the following configuration:

```
hosts:
  "*":
    listen:
      port: 8080
    paths:
      "/":
        proxy.reverse.url: http://132.226.1.140:80/
```

`132.226.1.140` is `h2o.examp1e.net`, but any host exhibits the issue.

When doing requests that expect a body but don't actually send one, h2o will keep the connection to the proxy host in `CLOSE_WAIT` forever. Here are 2 examples of such requests (frequently seen in the wild), with HTTP/1 and HTTP/2, using cURL:

```
$ curl --header "content-length: 0" 127.0.0.1:8080
$ curl -X GET --http2-prior-knowledge --data "" --header "content-length:" 127.0.0.1:8080
```

`netstat` gives:

```
tcp        1      0 192.168.1.1:34078     132.226.1.140:80        CLOSE_WAIT  1000       2602395    140006/./h2o
```
