### ISSUE TITLE
Request: Allow expires to be set on per mime basis

### ISSUE THREAD

**Issue by incognico** [h2o/h2o#2890]
Currently `expires:` can only be set at global/host/path/file level.

I'd like to set the expires on a mime or file extension basis. Example:
```
file.mime.settypes:
    "text/css":
         extensions: [".css"]
         is_compressible: yes
         priority: highest
         expires: 1 month
```
