### ISSUE TITLE
Uploads hang  (~16 Mo or ~22s), no data transmisted to "proxy.reverse.url"

### ISSUE THREAD

**Issue by trendymail** [h2o/h2o#3112]
Hello!

The issue is 100% reproductible on my setup so if you need more info, please tell me.

When uploading a file (to WordPress or PhpMyAdmin), h2o stops reading data after ~15/16 MB or after ~22s.

ssldump can't decrypt public trafic because RSA is not used.
tcpdump shows that no data is transfered to Apache (proxy.reverse.url).

h2o receives data from the browser, buffers it and then it stops.

No errors (either HTTP or in log files), no TCP reset, no HTTP Headers sent to proxy (ie: POST), nothing: it just hangs.

I have double-check Apache and PHP config files, everything seems fine but it does not matter because no data is transmitted to Apache.

Have a great day. :)

# ---

Browser -> Internet -> H2O (public IP) -> proxy.reverse.url -> Apache (internal IP)

h2o was compiled last night using commit [7e99771](https://github.com/h2o/h2o/tree/7e9977136b90b22f4a0607b89b93bdc50bbdf952).

- limit-request-body (undefined so 1 GB)
- handshake-timeout: 10
- temp-buffer-threshold: 100663296 (96 MB)
- http1-request-timeout: 30
- http2-idle-timeout: 30
- http2-graceful-shutdown-timeout: 30
- proxy.timeout.first_byte: 900000 (I know, this is insane...)
- proxy.timeout.keepalive: 30000
- proxy.reverse.url: "http://10.31.0.8:80/"

**Comment by trendymail** [comment]
Some news...

Long story short:

- building h2o with commit 79638c8b0323b958f2f316dc6dae98a5c694de5f (Feb 4, 2022) is OK, uploads are working fine.
- building h2o with commit b9a5ec634bb2d28695bf119f15436ce0a39b0d0c (Feb 7, 2022) is not OK, uploads "hang" with no reason/error

https://github.com/h2o/h2o/commits/master?after=8c2071fa787df2be527d54a07b268cee7c66b7c2+644&branch=master&qualified_name=refs%2Fheads%2Fmaster

To be more precise, uploading files to applications (PhpMyAdmin, websites, etc) still works fine with commit 79638c8b0323b958f2f316dc6dae98a5c694de5f (Merge pull request #2939 from miyagawa/perl-warnings) but not with the next immediate commit bc5222b45ceddf576fbfa539b8690908c593ea7e (Merge pull request #2929 from deweerdt/h3_err_desc).

I have checked twice, issue is 100% reproductible on my setup (browser => h2o (HTTP/2) => proxy.reverse.url => Apache (HTTP/1.1).

What I do not undersand is that Github shows just a few diff between theses two commit : https://github.com/h2o/h2o/commit/b9a5ec634bb2d28695bf119f15436ce0a39b0d0c

But, when I download the source code and compare it (diff -r -U5), there are **a lot** of differences.

https://github.com/h2o/h2o/archive/79638c8b0323b958f2f316dc6dae98a5c694de5f.zip
https://github.com/h2o/h2o/archive/bc5222b45ceddf576fbfa539b8690908c593ea7e.zip

Any hint will be greatly apreciated! :)

**Comment by fetus-hina** [comment]
I have a same (or similar) problem on my end.

  - Build/Runtime:
    - Revision: 13ba727ad12dfb2338165d2bcfb2136457e33c8a
    - OS: Rocky Linux 8 (Kernel 4.18.0 / kernel-4.18.0-425.13.1.el8_7.x86_64)
    - Compiler: GCC 8.5.0
    - SSL Lib.: OpenSSL 3.1.0 (static linked)
    - CMake options:
      - `-DCMAKE_BUILD_TYPE=Release`
      - `-DWITH_DTRACE=off`
      - `-DWITH_H2OLOG=off`
      - `-DWITH_MRUBY=off` (It also occurs when this option is turned on)
    - ```
      h2o version 2.3.0-DEV@13ba727ad
      OpenSSL: OpenSSL 3.1.0 14 Mar 2023
      fusion: YES
      ssl-zerocopy: YES
      ktls: YES
      ```

  - Notable configurations:
    - `limit-request-body: 4294967295` (4GB - 1)
    - Use PHP-FPM via UNIX socket (PHP 8.2.4)
    - ```yaml
      # removed some configurations and replaced hostname/path
      limit-request-body: 4294967295
      hosts:
        "foo.example.com:443":
          listen:
            port: 443
            ssl:
              key-file: /etc/pki/tls/certs/_.example.com.key
              certificate-file: /etc/pki/tls/certs/_.example.com.crt
              minimum-version: TLSv1.2
              cipher-suite: ECDHE-ECDSA-AES128-GCM-SHA256: #...
              cipher-preference: client
          paths:
            "/":
              file.dir: /var/www/sites/the-app/current/web
              redirect:
                url: /index.php/
                internal: yes
                status: 307
          file.custom-handler:
            extension: .php
            fastcgi.connect:
              port: /run/php-fpm/the-app.sock
              type: unix
      ```

  - Route to H2O: Browser → CloudFlare → H2O

  - Happens:
    - When POSTing data that containing a file of ~30 MiB, CloudFlare returns `HTTP 524` after a while (100 seconds, maybe)
      - Status `524` is "A timeout occurred" and it means "origin server (= H2O) doesn't return response data in 100 seconds."
      - Nothing is output to access log of H2O.
      - Nothing is output to error log of H2O.
      - Nothing is output to error log of PHP-FPM.
    - About 1 MiB data is processed without any problem.
    - Once `524` occurs, H2O doesn't shutdown normally.

I used `git bisect` to find the commit where the problem occurred.
Then, commit f07a474dd38cea7d7113c9da13cc4990cd9d8e71 was reported as it.

I doubt this result because this commit was merged in 2021 and enough time has passed.
However, the commit seems to add code to wait for HTTP/2 request bodies, so the symptoms seemed to match.

So, I decided to prohibit the use of HTTP/2 in requests from CloudFlare to the origin server(H2O).
![image](https://user-images.githubusercontent.com/848666/229341572-31886824-5b0b-4c28-9b0d-a670a759d9b9.png)
Then, the request that was failing above is now successfully completed.

From these results, it seems that H2O's HTTP/2 request processing has some problems.
