### ISSUE TITLE
How use websocket?

### ISSUE THREAD

**Issue by bulbulpaul** [h2o/h2o#313]
I use H2O and try websocket proxy.
But, it seems to be unavailable.

This is my setting.yml

``` yaml
    listen:
      port: 8080
    user: nobody
    default:
        paths:
          /:
            proxy.reverse.url: "http://127.0.0.1:9090/ws"
    access-log: /dev/stdout
    error-log: /dev/stdout
```

Request header and Response header.

```
    --- request header ---
    GET / HTTP/1.1
    Upgrade: websocket
    Connection: Upgrade
    Host: localhost:8080
    Origin: http://localhost:8080
    Sec-WebSocket-Key: jr94pSavSo6zv1OPbBxpmQ==
    Sec-WebSocket-Version: 13


    -----------------------
    --- response header ---
    HTTP/1.1 400 Bad Request
    Date: Mon, 11 May 2015 00:03:01 GMT
    Server: h2o/1.2.1-alpha1
    Connection: close
    Content-Length: 34
    content-type: text/html; charset=UTF-8
    upgrade: websocket
    -----------------------
```

Why do this request is bad_request?
Actually, the direct connection to Websocket server comes by request.

I'm afraid my expressions may be rude or hard to read, because I'm not so good at English.
