### ISSUE TITLE
Stream DASH traffic over HTTP/3 using h2o server

### ISSUE THREAD

**Issue by daymakhan23** [h2o/h2o#3173]
Hi all,

We are trying to stream DASH traffic over http3. 

We used **h2o** as http3 server and on the client side **dash.js player** is being used for playback (in chrome browser version 108.0.5359.98).

However, we observed that the stream (video chunks) are being transmitted over **HTTP/1.1** , although chrome supports **HTTP/3**.

Even when we are trying to simply load the home page of server (index.html) in Google chrome then that communication is also happening over HTTP/1.1. Using Firefox and cURL also we get the same results. 

So, we tried using the experimental version of cURL (with http3 support). In this case, the communication happens over HTTP/3 only when we explicitly use the _--http3_ option with cURL. But cURL doesn't provides support for DASH playback.

The expected behaviour is that the server should use HTTP/3 if the client supports it, else it must fall back to HTTP/2 or lower version. I have been using the configuration file provided in `examples/h2o/h2o.conf`.

Do I need to make any specific changes to the h2o server configuration file to use HTTP/3 as the default protocol while serving client requests?
Or some configuration is required on the client side?

Do we need to use a different DASH player that supports HTTP/3? If yes, then can you please suggest the name of any such player?

Thanks

**Comment by u5surf** [comment]
@daymakhan23 
Hi, I could play the stream DASH over HTTP/3.

Here is the demo on google chrome 116 in iOS.
https://github.com/h2o/h2o/assets/14180225/b1edbd2a-0835-4d5f-bdf5-6ec1536c7552


Here is the simplest but satisfiable of the configurations to be able to play mpeg DASH movie below.

conf/h2o.conf
```
hosts:
  "your.hostname":
    listen:
      port: 443
      type: quic
      ssl: &ssl
        certificate-file: fullchain.pem
        key-file: privkey.pem
        cipher-preference: server
        cipher-suite: "TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES
256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384"
    listen:
      port: 443
      ssl:
        <<: *ssl
    listen:
      port: 80
    header.add: "Alt-Svc: h3=\":443\";ma=60,quic=\":443\";ma=60"
    header.add: "Cache-Control: no-cache"
    paths:
      /:
        file.dir: doc
    access-log: /dev/stdout
    access-log: /dev/stdout
```


doc/index.html
```
<html>
    <head>
        <script src="https://cdn.dashjs.org/latest/dash.all.min.js"></script>
    </head>
    <body>
        <div>
            <div class="code">
                <video
                    data-dashjs-player=""
                    autoplay=""
                    src="./bigbuckbunny/bigbuckbunny.mpd"
                    controls="true"
                ></video>
            </div>
        </div>
    </body>
</html>
```
The video player page is made by referring to the site.
https://developers.cloudflare.com/stream/examples/dash-js/

doc
```
% tree -L 2 doc
doc
├── bigbuckbunny
│   ├── bigbuckbunny.mpd
│   └── dash
└── index.html
```
The mpeg dash files has hosted them with the copies of this.
https://github.com/bbc/exoplayer-testing-samples/tree/master/app/src/androidTest/assets/streams/files/bigbuckbunny
