### ISSUE TITLE
Serve single page apps

### ISSUE THREAD

**Issue by StefanoDeVuono** [h2o/h2o#326]
There should be an option under the `path` directive to serve any route or a series or routes so that a client-side single-page app can handle routing. This will dovetail particularly well with HTTP/2, since single-page apps can make great use of features like eager loading of the app through multiplexed requests and partial updates through server pushes.

**Comment by kazuho** [comment]
That sounds like a good idea!  Will look into how I should implement the feature.

**Comment by kazuho** [comment]
Since 1.3, the `redirect` directive of H2O supports internal redirect.  By using the feature, it is possible to send single file to any response by using a configuration like:

```
paths:
  /:
    file.dir: /path/to/doc-root
    redirect:
      url: /index.html? # redirect all requests to `index.html?...`
      internal: YES
      status: 307
```

The configuration redirects all requests (that targetted a non-existing file) to `/path/to/doc-root/index.html`.

The other way would be to use the mruby handler coming to 1.5.  Once #471 gets merged it would become possible to use mruby to configure the equivalent, like:

```
paths:
  /:
    mruby.handler: |
      H2O::Request.new.send_file("/path/to/the-only-html-file")
```
