### ISSUE TITLE
binding to python and golang???

### ISSUE THREAD

**Issue by aguai** [h2o/h2o#338]
is there any guide to run python or golang application on h2o???
or any resource??

**Comment by qgy18** [comment]
like this:

```
paths:
  /:
    proxy.reverse.url: http://127.0.0.1:9090/
    proxy.preserve-host: ON
```

h2o only supports HTTP/1.x proxy, no fastcgi or wsgi.
