### ISSUE TITLE
NULL byte (%00) in path causes infinite 301 redirects instead of 400 Bad Request

### ISSUE THREAD

**Issue by Srinut22** [h2o/h2o#3483]
We're encountering unexpected behavior in h2o when requesting a path containing a URL-encoded null byte (%00). Instead of rejecting the request or returning a 400 Bad Request, h2o responds with a 301 Moved Permanently and redirects to the same path. Following the redirect results in a loop.

We ran the h2o server in a Docker container on port 8080.
Request: 
` curl "http://localhost:8080/%00"`
Response:
`<!DOCTYPE html><TITLE>Moved</TITLE><P>The document has moved <A HREF="/%00/">here</A>`

Following redirects, we get:
`curl -L "http://localhost:8080/%00"`
Response:
`curl: (47) Maximum (50) redirects followed`

Server configuration:
```
# h2o.conf
user: root
hosts:
  "default":
    listen:
      port: 80
    paths:
      "/":
        file.dir: /usr/share/h2o/htdocs
```
Environment:
```
h2o version 2.2.5
OpenSSL: OpenSSL 3.0.2 15 Mar 2022
mruby: YES
```
