### ISSUE TITLE
How to map sub domain to sub folder?

### ISSUE THREAD

**Issue by AssemblyXiang** [h2o/h2o#451]
e.g. ```abc.xx.com``` map to ```/abc/```

**Comment by kazuho** [comment]
You can have multiple entries within `hosts` section, each of them having different directories specified in their `paths` section by using `file.dir`.

If you want to do rule-based mapping (i.e. map any subdomain name to a directory with the same name), you would need to generate the configuration file that lists every subdomain name (under the `hosts` section) and the corresponding directory name.

**Comment by AssemblyXiang** [comment]
Thank you for reply!

**Comment by jodosha** [comment]
@kazuho Isn't there a way to get dynamic subdomains?

With Nginx you can do:

```
server {
  server_name ~^(.*)\.example\.com$ ;
  root www/pub/$1;
}
```
[Source: http://serverfault.com/a/250219]

---

For an upcoming project we need to use separated subdomains for each customer eg: `https://jodosha.example.com`.

Manually adding entries to configuration and restart the server isn't the ideal workflow. Is it possible to have a rewrite rule like the one described above?

I want to push h2o adoption for this client of mine. I hope to convince them :+1: Thanks for your time. :smile:

**Comment by kazuho** [comment]
@jodosha You can use mruby handler with `reproxy` set to `on`.

Please refer to https://h2o.examp1e.net/doc/configure/mruby_directives.html#delegating-request for how delegations works.

A simple example would look like this (not tested):
```yaml
hosts:
  "example.com":
    paths:
      "/":
        reproxy: ON
        mruby.handler: |
          lambda do |env|
            if /\A(.*)\.example\.com\z/.match(env["HTTP_HOST"])
              # internally redirect foo.example.com to example.com/foo
              return [307, {"x-reproxy-url" => "http://example.com/#{$1}#{env["REQUEST_URI"]}" }, []]
            end
            return [399, {}, []] # do not modify the request
          end
        file.dir: "www/pub"
```

Note that the example levarages from the first entry in the `hosts` being a catch-all entry (i.e. it would be selected if there is no entry for the hostname supplied by the cilent via the `host` header exists in the configuration).

You could also use a wildcard host entry in 1.7 beta series (see #634); however make sure to use 1.7.0-beta4 in such case, since the mruby handler in earlier beta releases contain regressions.
