### ISSUE TITLE
Bind on both ips, IPv4 and IPv6 syntax

### ISSUE THREAD

**Issue by webhtb** [h2o/h2o#531]
I try this and the h2o start only on IPv4, what i miss?

hosts:
  "cloud.soft-manager.ro:80":
    listen:
      host: 185.72.242.70
      port: 80
      host: 2a04:2b87:1::6
      port: 80

**Comment by kazuho** [comment]
You should write:
```
hosts:
  "cloud.soft-manager.ro:80":
    listen:
      host: 185.72.242.70
      port: 80
    listen:
      host: 2a04:2b87:1::6
      port: 80
```
