### ISSUE TITLE
Wildcard hosts

### ISSUE THREAD

**Issue by guilhem** [h2o/h2o#543]
I don't find any documentation or any way to use a wildcard for hosts.
I need this for something like that:

```yaml
  "www.example.io":
    paths:
      "/":
        proxy.reverse.url: http://127.0.0.1:8080/

  "*.example.io":
    paths:
      "/":
        proxy.reverse.url: http://127.0.0.1:8081/
  "*.foo.com":
    paths:
      "/":
        proxy.reverse.url: http://127.0.0.1:8082/
```

It's true this kind of feature imply to have some variables like `$HOST` (for example), to use it for:
```yaml
  "*.example.com":
    paths:
      "/":
        redirect: https://$HOST/
```
