### ISSUE TITLE
h2o reverse proxy crashed when front end connections were dropped

### ISSUE THREAD

**Issue by tatsuhiro-t** [h2o/h2o#61]
I setup h2o in reverse proxy mode like this:
```yml
hosts:
  default:
    paths:
      /:
        proxy.reverse.url: http://127.0.0.1:18080
        proxy.keepalive: ON
```
And start load testing with h2load.  While load testing, I terminated h2load then h2o crashed with these messages:
```
h2o: /path/h2o/lib/proxy.c:235: on_generator_dispose: Assertion `self->client == ((void *)0)' failed.
```
