### ISSUE TITLE
Expires for certain extensions

### ISSUE THREAD

**Issue by utrenkner** [h2o/h2o#623]
https://h2o.examp1e.net/configure/expires_directives.html says that expires can be used at any of these levels: global, host, path, extension

However, I could not find any example for the use of "extension" except in connection with file.custom-handler. I tried several things, but did not manage to get h2o to accept my configuration.

My goal is to set static assets (.jpg, .png, .css, .js etc.) to "expires: 365 day"

Or to set everything to "expires: 365 day" and to exclude files with extension ".php" from it.

How would I achieve this?

**Comment by kazuho** [comment]
That's a good question!

I have added an example to https://h2o.examp1e.net/configure/mruby_directives.html#modifying-response.

**Comment by utrenkner** [comment]
Thank you - this is very helpful!

**Comment by jakobg** [comment]
Hi @kazuho,

I think the link you have posted to the example is not correct anymore. Can you provide an example to how to use the **extension**-level. 

I would assume to do the following:

```
hosts:
  "domain:80":
    listen:
      port: 80
    paths:
      "/":
        file.dir: /var/www
        expires: 1 day
           extension: .png
```

Under https://h2o.examp1e.net/configure/mruby.html#modifying-response you give an example with mruby. Is this the only way for now?
