### ISSUE TITLE
support upstream server using HTTPS (was: proxy.reverse.url acts like a redirect)

### ISSUE THREAD

**Issue by pierrebeaucamp** [h2o/h2o#64]
Hi, 
I use this simple configuration file to get content from a public cloud storage:

```
listen: 80
hosts:
  default:
    paths:
      /:
        proxy.reverse.url: http://foo.googledrive.com/host/bar/
    access-log: /var/log/h2o 
```

The similar config in Nginx would be:

```
server {
        listen       80;
        location / {
           proxy_pass http://foo.googledrive.com/host/bar/;
        }
    }
```

But instead of having h2o proxy the content from the cloud storage, my browser gets redirected to `http://foo.googledrive.com/host/bar/`.  (By 301 Moved Permanently)
