### ISSUE TITLE
h2o mruby hello example leaks memory

### ISSUE THREAD

**Issue by mingodad** [h2o/h2o#699]
Hello !
I just did a fresh build of h2o and tested it with httpress/ab and the memory usage only gorws at each request, till I kill it to not freeze my computer.

Probably the problem is with mruby module, the hello.rb example only show it.

Cheers !

examples/h2o_mruby/h2o.conf with logs redirected to /dev/null
``` 
# to find out the configuration commands, run: h2o --help

listen: 8080
listen:
  port: 8081
  ssl:
    certificate-file: examples/h2o/server.crt
    key-file: examples/h2o/server.key
hosts:
  "127.0.0.1.xip.io:8080":
    paths:
      /:
        file.dir: examples/doc_root
        mruby.handler-file: examples/h2o_mruby/hello.rb
    access-log: /dev/null
  "alternate.127.0.0.1.xip.io:8081":
    listen:
      port: 8081
      ssl:
        certificate-file: examples/h2o/alternate.crt
        key-file: examples/h2o/alternate.key
    paths:
      /:
        file.dir: examples/doc_root.alternate
    access-log: /dev/null
```
```
./h2o --conf=examples/h2o_mruby/h2o.conf

httpress -t 2 -n 500000 -c 50 -k http://127.0.0.1:8080/hello
ab -n 500000 -c 50 -k http://127.0.0.1:8080/hello

```
