### ISSUE TITLE
Multiple listen on https, works only one, last

### ISSUE THREAD

**Issue by webhtb** [h2o/h2o#717]
Hi, i try to use multiple listen in one hosts and i discover only the h2o respond only in last ip.
Also i checked on netstat, the h2o bind in all ips but respond to browsers only in last ip, it is about any https host

```
  "host.com:443":
    listen:
      host: 192.168.0.101
      port: 443
    listen:
      host: 127.0.0.1
      port: 443
      ssl:
        certificate-file: /var/www/ssl/cert.crt
        key-file: /var/www/ssl/key.key
    paths:
      "/":
........
```

**Comment by kazuho** [comment]
Is my assumption correct that you want to server `HTTPS` (not `HTTP`) on `192.168.0.101:443`?

If that is the case, you should define `ssl` attribute to the listen directive for `192.168.0.101:443`.

**Comment by webhtb** [comment]
It is listen, also no matter the ip, i discover this with real domains and real ips, this is only to reproduce local and i got same result. I told you, the h2o make bind on all ips but respond to browsers only for last ip in the list. Why multiple? Because one ipv4 and one ipv6 for each vhost.

**Comment by kazuho** [comment]
> h2o make bind on all ips but respond to browsers only for last ip in the list.

Doesn't the server respond to the browser if you access the address using __HTTP__ (not HTTPS)?

What I am saying is that you should write something like:
```
  "host.com:443":
    listen:
      host: 192.168.0.101
      port: 443
      ssl:                                       # this attribute is required to have this listen accept HTTPS connections
        certificate-file: /var/www/ssl/cert.crt  # 
        key-file: /var/www/ssl/key.key           #
    listen:
      host: 127.0.0.1
      port: 443
      ssl:
        certificate-file: /var/www/ssl/cert.crt
        key-file: /var/www/ssl/key.key
    paths:
      "/":
........
```
