### ISSUE TITLE
Can't set the charset using file.mime.addtypes

### ISSUE THREAD

**Issue by TheDecryptor** [h2o/h2o#730]
I tried using the configuration specified in https://github.com/h2o/h2o/issues/260#issuecomment-87954163 on my site, but didn't have any success. With a fresh installation of 1.6.3 and the following cut down configuration file, h2o still sends the default mime-type for html files, not my provided one with a charset parameter.

```
file.mime.addtypes:
    "text/html; charset=utf-8": ".html"
listen:
    port: 8080
hosts:
    "localhost":
        paths:
            /:
                file.dir: /path/to/www
```

It seems that I can't override any default provided mime-type, only unknown ones apply.
