### ISSUE TITLE
allow definition of a mime-type without extensions

### ISSUE THREAD

**Issue by kazuho** [h2o/h2o#732]
As of now, the mimemap structure requires that at least one extension to be mapped for every mime-type.

However for example if we have a definition like following in the configuration file, the default mapping for `text/css` gets removed, since the mapping for its only extension (i.e. `.css`) is overwritten.  This causes an unwanted side-effect that it invalidates the priority modification in case a FastCGI application returns a response with `text/css` wo. charset set as the content-type.

```
file.mime.add-types:
  "text/css; charset=utf-8":
    extensions: [".css"]
    is_compressible: yes
    priority: highest
```
