### ISSUE TITLE
Better reverse-proxy support

### ISSUE THREAD

**Issue by dantman** [h2o/h2o#741]
I'd like to use h2o primarily as a reverse proxy that'll provide SSL termination and HTTP/2 support (which is better than any other server I'd consider using) for my varnish and nginx backends.

The problem is, `proxy.reverse.url` is part of `paths` which is only valid in the `host` context. This means A) it's impossible to proxy all your sites without explicitly defining a host for every single hostname you use; and B) the h2o config file gets massive due to all the duplicate configs.

Ideally it would be possible to define a `paths` in `global` context so you could listen globally to port `80`, add https hosts listening on 443 for the ssl config, and reverse proxy all that to the same webserver.

Something easier to implement that would also help a bit would be a way to define some common config and include it elsewhere in the file. Such as an `include`/`includes` setup:

```yaml
includes:
  proxy:
    "/":
      proxy.reverse.url: "http://127.0.0.1:80"
      proxy.preserve-host: ON
hosts:
  "vancouver-anime.com":
    listen: 80
    listen:
      port: 443
      ssl:
        certificate-file: ...
        key-file: ...
    paths:
      include: proxy
  # more hosts with similar config
```

**Comment by kazuho** [comment]
Thank you for the suggestion.

You can do something similar by using YAML anchors.  The example below sets an anchor named `default_paths` to the first `paths` element, and re-uses it afterwards.

```yaml
hosts:
  "example.com":
    listen:
      port: 443
      ssl:
        certificate-file: /path/to/example.com.crt
        key-file:         /path/to/example.com.crt
    paths:  &default_paths
      "/":
        file.dir: /path/to/doc-root
  "example.org":
    listen:
      port: 443
      ssl:
        certificate-file: /path/to/example.org.crt
        key-file:         /path/to/example.org.crt
    paths:  *default_paths
```
