### ISSUE TITLE
using uwsgi

### ISSUE THREAD

**Issue by bax-** [h2o/h2o#744]
I'm having problems serving a python application via uwsgi with h2o.

I'm on FreeBSD 10.2 with h20 1.6.3.

This is the relevant part of my `h2o.conf`:

```
hosts:
    "hostname.com":
        paths:
            "/":
                file.dir: /usr/local/www/

            "/modoboa":
                file.dir: /usr/local/www/modoboa_default/modoboa_default/
                proxy.reverse.url: http://[unix:/tmp/uwsgi.sock]/
                proxy.timeout.keepalive: 1000
                proxy.preserve-host: ON

            "/modoboa/sitestatic/":
                file.dir: /usr/local/www/modoboa_default/sitestatic/

            "/modoboa/media/":
                file.dir: /usr/local/www/modoboa_default/media/
```

And my `uwsgi.ini`:

```
[uwsgi]
chdir = /usr/local/www/modoboa_default
module = modoboa_default.wsgi:application
master = true
harakiri = 60
processes = 4
vhost = true
no-default-app = true
```

When I open `hostname.com/modoboa` in browser, I get a `I/O error (head)` in the browser.

This is in the `/var/log/h2o/h2o-error.log`

```
[lib/core/proxy.c] in request:/modoboa:I/O error (head)
```

Anything I'm missing?

**Comment by kazuho** [comment]
I believe you should configure uwsgi to use the HTTP protocol.  Please refer to http://uwsgi-docs.readthedocs.org/en/latest/HTTP.html

**Comment by bax-** [comment]
Thank you for pointing me there. 
I wasn't aware of this.
The only resource I had found didn't mention it:
https://github.com/achiku/sample-h2o-uwsgi

**Comment by bax-** [comment]
I'm still struggling.
I got it to connect vie http-socket but now no python application is being found.

How would I set the uwsgi params that I'm used to from nginx?

```
location /modoboa/ {
        root /usr/local/www/modoboa_default/modoboa_default;
        include uwsgi_params;
        uwsgi_pass unix:/tmp/uwsgi.sock;
        uwsgi_param UWSGI_SCRIPT modoboa_default.wsgi:application;
        uwsgi_param UWSGI_SCHEME https;
        uwsgi_param SCRIPT_NAME /modoboa;
        uwsgi_modifier1 30;
    }
```

**Comment by csmk** [comment]
Hi, I'm sorry for the _necrobump_, but did you figured this out? I've similar setup, so all I did was this:

On uwsgi side:
```
[uwsgi]
pidfile = /run/uwsgi_mdb/mdb.pid
http-socket = 127.0.0.1:2001

cheaper = 2
workers = 6
cheaper-step = 1

vacuum = true
no-default-app = true

plugins = python27
virtualenv = /srv/modoboa/venv
chdir = /srv/modoboa/mdb
module = mdb.wsgi:application
```

Then on H2O side:
```
  "example.com:443":
    access-log: /var/log/foo/bar.log
    paths:
      "/":
        proxy.preserve-host: ON
        proxy.reverse.url: "http://127.0.0.1:2001/"
      "/sitestatic":
        file.dir: /srv/modoboa/mdb/sitestatic
```

If this solves your issue or if you already solved it, please close this one.

Cheers

**Comment by bax-** [comment]
Thanks for bringing this up again.

This is the resolution that worked for me:

`/usr/local/etc/h2o/h2o.conf`
```
hosts:
    "example.com":
        #fastcgi.send-delegated-uri: ON
        paths:
            "/":
                file.dir: /usr/local/www/

        # adminer
            "/adminer":
                file.dir: /usr/local/www/adminer/
                file.index: ['index.php']

        # modoboa
            "/modoboa":
                #fastcgi.connect:
                #    port: /tmp/uwsgi-fastcgi.sock
                #    type: unix
                proxy.reverse.url: "http://[unix:/tmp/uwsgi-http.sock]/modoboa"
                proxy.timeout.keepalive: 1000
                proxy.preserve-host: ON

            "/modoboa/sitestatic":
                file.dir: /usr/local/www/modoboa_default/sitestatic/

            "/modoboa/media":
                file.dir: /usr/local/www/modoboa_default/media/
```

`/usr/local/etc/uwsgi/modoboa.ini`
```
[uwsgi]
# Not needed when using uwsgi from pip
#plugins = python
chdir = /usr/local/www/modoboa_default
#module = modoboa_default.wsgi:application
#master = true
harakiri = 60
processes = 4
#vhost = true
#no-default-app = true

#TEST H2O
http-socket = /tmp/uwsgi-http.sock
#http = /tmp/uwsgi-http.sock
#http-socket-modifier1 = 30
#fastcgi-socket=/tmp/uwsgi-fastcgi.sock
#memory-report=True
enable-threads = true
#limit-as=512
#processes=1
#buffer-size=60000
#http-keepalive=3000
#wsgi-file = modoboa_default/wsgi.py
mount = /modoboa=modoboa_default.wsgi:application
manage-script-name = true
#route = ^/ uwsgi:,30,0
#uwsgi-socket-modifier1 = 30
#route = ^/(.) redirect:http://www.google.com
``
