### ISSUE TITLE
merging of settings

### ISSUE THREAD

**Issue by bax-** [h2o/h2o#758]
Do I need to re-enter rules in a smaller context that I already defined in global context in this case?

```
listen:
    host: 10.0.0.2
    port: 443
    ssl:
        minimum-version: TLSv1.2
        # generate your own certificates
        certificate-file: /usr/local/etc/h2o/server.crt
        key-file: /usr/local/etc/h2o/server.key

hosts:
    my.example.com:443
        listen:
            ssl:
                        certificate-file: /usr/local/etc/h2o/my.example.com/server.crt
                        key-file: /usr/local/etc/h2o/my.example.com/server.key
```

Do I have to give `port: 443` again?
Is the ssl minimum-version taken from the first definition?
