### ISSUE TITLE
several path directives

### ISSUE THREAD

**Issue by bax-** [h2o/h2o#759]
Is it possible to use several path directives under one host?
I'm trying to use YAML aliases to shorten my configuration.
I would love to do this:

```
listen:
    host: 127.0.0.1
    port: 80
listen:
    host: xxx:xxx:xx:::x
    port: 80
listen:
    host: 127.0.0.1
    port: 443
listen:
    host: xxx:xxx:xx:::x
    port: 443

hosts:
  default:
    paths: "/"
        file.dir: /path/to/doc-root
    paths: &acme
      ".well-known/acme-challenge/":

  "example.org:443":
    listen:
      ssl:
        certificate-file: /path/to/example.org.crt
        key-file:         /path/to/example.org.crt
    paths:"/"
      proxy.reverse.url: "http://127.0.0.3:8080/"
    paths: *acme
```
