### ISSUE TITLE
wildcard URLs

### ISSUE THREAD

**Issue by bax-** [h2o/h2o#760]
Is there a prioritization when using wildcard URLS?
for example, could I define host *.example.com and also subdomain.example.com, so that subdomain2.example.com would be fetched by the wildcard but subdomain.example wouldn't?

**Comment by kazuho** [comment]
Does the following sentence in https://h2o.examp1e.net/configure/base_directives.html#hosts answer your question?
> Note that an exact match is preferred over host definitions using wildcard characters.

**Comment by bax-** [comment]
thanks. I overlooked. Sorry.

**Comment by bax-** [comment]
I got infinite rewrites with this:

```
"example.com":
    paths: &redirect
      "/":
        redirect:
          status: 301
          url: https://www.example.com/
  "*.example.com":
    paths: *redirect
  "example.org":
    paths: *redirect
  "*.example.org":
    paths: *redirect
  "www.example.com":
    access-log: /var/log/h2o/www.example.com.log
    listen:
      host: *ip4
      port: 443
      ssl: &ssl_www
        dh-file: *dh-file
        cipher-preference: *cipher-preference
        cipher-suite: *cipher-suite
        certificate-file: …
        key-file:         …
    listen:
      host: *ip6
      port: 443
      ssl: *ssl_www
    paths:
```

I had to comment out the wildcard statements…
