### ISSUE TITLE
multiple IPs: Bind in host level

### ISSUE THREAD

**Issue by bax-** [h2o/h2o#764]
I have multiple IPs that I bind to specifically on global level:

```
listen:
    host: 10.0.0.2
    port: 80
listen:
    host: XXX:XXX:XXX:::X
    port: 80
listen:
    host: 10.0.0.2
    port: 443
    ssl: &SSL
      minimum-version: TLSv1.2
      dh-file: /usr/local/etc/ssl/dhparam4096.pem
      cipher-preference: server
      cipher-suite: ECDHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RS
A-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA
      certificate-file: /usr/local/etc/ssl/ABCD.crt
      key-file:         /usr/local/etc/ssl/ABCD.key
listen:
    host: XXX:XXX:XXX:::X
    port: 443
    ssl: *SSL
```

I was expecting that when I use this in global, that the settings were also used when I used the same ports inside hosts, e.g.
```
"ABCD2.com:80":
    paths:
      "/":
        redirect:
          status: 301
          url: https://ABCD2.com/
  "ABCD2.com:443":
    header.add: "strict-transport-security: max-age=15768000; includesubdomains; preload"
    access-log: /var/log/h2o/ABCD2.com.log
    listen:
      port: 443
      ssl:
        certificate-file: /usr/local/etc/ssl/ABCD2.crt
        key-file:         /usr/local/etc/ssl/ABCD2.key
    paths:
      "/":
        proxy.reverse.url: "http://10.0.0.13/"
```

But this gives me
```
failed to bind to [::]:443:Address already in use at /usr/local/share/h2o/start_server line 9.
```
So do I have to define the listen directive inside every host for each IP?
That adds seven lines in each host and seems redundant…
Am I missing something? Is there a way to write this smarter / shorter that I'm not seeing?
