### ISSUE TITLE
make more apparent which ssl attributes have to be set individually

### ISSUE THREAD

**Issue by bax-** [h2o/h2o#772]
I have "default" ports and host IPs set in global context:

```
listen:
    host: &ip4 10.0.0.2
    port: 80
listen:
    host: &ip6 XX:XX:XX:XX::XX
    port: 80
listen:
    host: *ip4
    port: 443
    ssl: &SSL
      minimum-version: TLSv1.2
      dh-file: &dh-file /usr/local/etc/ssl/dhparam4096.pem
      cipher-preference: &cipher-preference server
      cipher-suite: &cipher-suite DHE-RSA-CHACHA20-POLY1305:EDH+CAMELLIA:EDH+aRSA:ECDHE-RSA-CHACHA20-POLY1305:EECDH+aRSA+AESGCM:EECDH+aRSA+SHA256:EECDH:+CAMELLIA128:+AES128:+SSLv3:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!DSS:!RC4:!SEED:!IDEA:!ECDSA:kEDH:CAMELLIA128-SHA:AES128-SHA
      certificate-file: /usr/local/etc/ssl/certs/www.example.com/fullchain.pem
      key-file:         /usr/local/etc/ssl/certs/www.example.com/privkey.pem
listen:
    host: *ip6
    port: 443
    ssl: *SSL
```

It makes little sense in my case that I have to define certificate and key to make h2o start although they will be redefined in the hosts' configs.

```
"subdomain.example.com:80":
    paths:
      "/":
        redirect:
          status: 301
          url: https://subdomain.example.com/
  "subdomain.example:443":
    header.setifempty: "strict-transport-security: max-age=15768000; includesubdomains; preload"
    access-log: /var/log/h2o/subdomain.example.com.log
    listen:
      host: *ip4
      port: 443
      ssl: &ssl_subdomain
        dh-file: *dh-file
        cipher-preference: *cipher-preference
        cipher-suite: *cipher-suite
        certificate-file: /usr/local/etc/ssl/certssubdomain.example.com/fullchain.pem
        key-file:         /usr/local/etc/ssl/certs/subdomain.example.com/privkey.pem
    listen:
      host: *ip6
      port: 443
      ssl: *ssl_subdomain
    paths:
      "/":
        proxy.reverse.url: "http://10.0.0.10/"
      "/.well-known/acme-challenge": *acme
```

I found out that if I redefine `ssl:` in a host's context (which of course I have to since I have to use different certificates and keys) that I have to re-set `dh-file`, `cipher-preference` and `cipher-suite` in the individual context again to override the defaults.

`minimum-version`, however, seems OK to be set only once in global context.

It would be nice if these details would make it into the documentation.

If I'm doing anything wrong here of if I'm misinterpreting anything, please enlighten me!
