### ISSUE TITLE
Feature Request : Load balancing - Proxy - Cluster

### ISSUE THREAD

**Issue by dtruffaut** [h2o/h2o#775]
h2o is an amazing tool !

Today it can challenge Varnish with the cache aware server push feature (http2-casper) that brings cache logic and memory consumption to the client. That is a great improvement.

Tomorrow, with the ability to proxify requests to a cluster of backends, it can even challenge load balancers like HAProxy or NginX.

Here is a proposal of a very basic declaration example of a cluster :
```
cluster: &default_cluster
  - http://127.0.0.1:8080
  - http://127.0.0.1:8081
  - http://127.0.0.1:8082

hosts:
  "example.com":
    listen:      
        ...
    paths: &default_paths      
      "/":
        proxy.reverse.url: *default_cluster
```

Notes: 
Clusters IP can be internal or external
Clusters can be defined at multiple levels (global, host, ...)
Multiple clusters can defined (one for backend, one for backoffice, one for files, ...etc.)
Clusters be used with the reproxy directive

NginX Upstream :
http://nginx.org/en/docs/http/ngx_http_upstream_module.html

Related issues : 
https://github.com/h2o/h2o/issues/90
