### ISSUE TITLE
ciphers inherited when cert files match?

### ISSUE THREAD

**Issue by bax-** [h2o/h2o#818]
This is a part of my config:

```
 "push.example.com:80":
    paths:
      "/":
        redirect:
          status: 301
          url: https://push.example.com/
  "push.example.com:443":
    header.setifempty: "strict-transport-security: max-age=15768000; includesubdomains; preload"
    access-log: /var/log/h2o/push.bastianbeutttel.com.log
    listen:
      host: 10.0.0.2
      port: 443
      ssl: &ssl_push
        dh-file: *dh-file
        cipher-preference: *cipher-preference
        cipher-suite: ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-CHACHA20-POLY1305:EDH+aRSA+AES256:EECDH+aRSA+AES256:!SSLv3
        certificate-file: /usr/local/etc/ssl/certs/tools.example.com/fullchain.pem
        key-file:         /usr/local/etc/ssl/certs/tools.example.com/privkey.pem
    listen:
      host: XX:XX:XX:XX:XX
      port: 443
      ssl: *ssl_push
    paths:
      "/":
        proxy.reverse.url: "http://10.0.0.12/"
      "/.well-known/acme-challenge": *acme

  "tools.example.com:80":
    paths:
      "/":
        redirect:
          status: 301
          url: https://tools.example.com/
  "tools.example.com:443":
    header.setifempty: "strict-transport-security: max-age=15768000; includesubdomains; preload"
    access-log: /var/log/h2o/tools.bastianbeutttel.com.log
    listen:
      host: 10.0.0.2
      port: 443
      ssl: &ssl_tools
        dh-file: *dh-file
        cipher-preference: *cipher-preference
        cipher-suite: *cipher-suite
        certificate-file: /usr/local/etc/ssl/certs/tools.example.com/fullchain.pem
        key-file:         /usr/local/etc/ssl/certs/tools.example.com/privkey.pem
    listen:
      host: XX:XX:XX:XX:XX
      port: 443
      ssl: *ssl_tools
    paths:
      "/":
        proxy.reverse.url: "http://10.0.0.10/"
      "/.well-known/acme-challenge": *acme
```

the second host (`tools.example.com`) uses the same cipher as the first one although `*cipher-suite` is declared in global context like this:

```
listen:
    host: 10.0.0.2
    port: 443
    ssl: &SSL
        minimum-version: TLSv1.2
        dh-file: &dh-file /usr/local/etc/ssl/dhparam4096.pem
        cipher-preference: &cipher-preference server
        # https://calomel.org/h2o.html
        #cipher-suite: &cipher-suite ECDHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA
        # https://bettercrypto.org
        #cipher-suite: &cipher-suite EDH+CAMELLIA:EDH+aRSA:EECDH+aRSA+AESGCM:EECDH+aRSA+SHA256:EECDH:+CAMELLIA128:+AES128:+SSLv3:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!DSS:!RC4:!SEED:!IDEA:!ECDSA:kEDH:CAMELLIA128-SHA:AES128-SHA
        # https://wiki.mozilla.org/Security/Server_Side_TLS#Modern_compatibility
        cipher-suite: &cipher-suite ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256
        certificate-file: /usr/local/etc/ssl/certs/www.example.com/fullchain.pem
        key-file:         /usr/local/etc/ssl/certs/www.example.com/privkey.pem
```

All hosts that use a unique certificate and key file use the correct cipher (`&cipher-suite`).
