### ISSUE TITLE
Allow running of cgi-scripts without file extensions

### ISSUE THREAD

**Issue by tobybryans** [h2o/h2o#852]
I'm trying to set up h2o instead of apache httpd on a customer site which uses mailman. The cgi-scripts provided by mailman do not have any extensions but instead are all in a /cgi-bin/ folder. I tried:
```
      /mailman/:
        file.dir: /u01/app/mailman/cgi-bin/
        fastcgi.spawn:
          command: "exec /u01/app/h2o/share/h2o/fastcgi-cgi"
          user: mailman
```
but this just fetched the file from the cgi-bin folder. Since the files do not have an extension I can't catch them with file.extension. Is there another way?

**Comment by kazuho** [comment]
@tobybryans The following will do if all files under cgi-bin are CGI scripts.
```
/mailman/:
  fastcgi.spawn:
    command: "exec /u01/app/h2o/share/h2o/fastcgi-cgi"
    user: mailman
```
