### ISSUE TITLE
download *.php file - not execute or open php. 

### ISSUE THREAD

**Issue by Winzigweich** [h2o/h2o#876]
hello, my configuration file is: 

access-log: /var/www/vhosts/system/affilie.de/logs/proxy_access_ssl_log
error-log: /var/www/vhosts/system/affilie.de/logs/error_log
expires: off
file.dirlisting: off
file.send-compressed: on

limit-request-body: 1024

pid-file: /var/run/h2o.pid
user: root

file.mime.addtypes:
   "text/html; charset=utf-8": .html

ssl-session-resumption:
   mode: all

hosts:
  "HTTP server, redirect all requests to https":
   listen:
      host: 217.160.108.85
      port: 80
   paths:
     /:
       redirect:
         status: 301
         url: https://www.affilie.de/

  "HTTPS server":
   listen:
      host: 217.160.108.85
      port: 4444
      ssl:
        certificate-file: /opt/psa/var/certificates/cert-FhvkAw
        key-file: /opt/psa/var/certificates/cert-FhvkAw
        cipher-preference: server
        cipher-suite: ECDHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA
        minimum-version: TLSv1.2
   paths:
     /:

      file.dir: /var/www/vhosts/abonne-affilie.de/httpdocs/wordpress

      header.add: "cache-control: public, max-age=31556926"
      header.add: "strict-transport-security: max-age=31556926; includesubdomains; preload"
      header.add: "x-frame-options: deny"

in browser all *.php files will open or save, not execute. 
have anyone a idea?

**Comment by fetus-hina** [comment]
You should use the PHP-FPM (Fast-CGI) and the internal-redirect mechanism.
Like this:
```
# ...
paths:
  "/":
    file.dir: /var/www/vhosts/abonne-affilie.de/httpdocs/wordpress
    redirect:
      url: /index.php/
      internal: YES
      status: 307

file.custom-handler:
  extension: .php
  fastcgi.connect:
    host: 127.0.0.1
    port: 9000
    type: tcp
```
Of course, you should configure and run PHP-FPM daemon.

You can find more information (and another way) on [this post](http://blog.kazuhooku.com/2015/06/h2ophpmodrewrite.html) (in Japanese...)
