### ISSUE TITLE
Is it possible to give an example using unix socket 

### ISSUE THREAD

**Issue by mingodad** [h2o/h2o#94]
I saw on src/main.c that it's possible to specify unix domain sockets for the server, but no example is provided.

Can we have an example with unix socket and also a client example ?

Cheers !

**Comment by mingodad** [comment]
h2o_parse_url do not recognize unix sockets.

**Comment by cubicdaiya** [comment]
`h2o` supports to listen unix sockets. The example is below.

```yml
listen:
  port: /tmp/h2o.sock
  type: unix
hosts:
  default:
    paths:
      /:
        file.dir: examples/doc_root
    access-log: /dev/stdout
```

But any other supports for unix sockets are not enough yet.
